// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2025 OpenCHAMI Contributors

/*
Package group defines the Group resource for template-based node group configurations.

A Group represents a collection of HPC nodes that should receive the same cloud-init
configuration. Each group contains a Jinja2 template that is rendered with cluster
defaults and node-specific data to produce cloud-init configuration in YAML format.

# Resource Structure

The Group resource consists of:

	Metadata:
	  - Name: Logical name of the group (e.g., "compute", "login", "storage")
	  - UID: Unique identifier generated by storage system
	  - Created, Updated: Timestamps for audit trails

	Spec (Specification):
	  - Template: Jinja2 template string that produces valid YAML cloud-init config
	  - MetaData: Custom key-value metadata injected as template variables
	  - Description: Human-readable group description

	Status (Current State):
	  - ValidationError: Error message if template validation failed
	  - TemplateHistory: Last 10 template versions with hashes and validation results
	  - LastTemplateVersion: SHA256 hash of current template
	  - LastValidation: Timestamp of last validation attempt

# Template Rendering

When a node requests group configuration via /{group}.yaml endpoint, the template is
rendered with the following variables:

	From ClusterDefaults (cluster-wide):
	  - cluster_name: Cluster identifier
	  - base_url: Base URL for cloud-init service
	  - cloud_provider: Cloud provider (aws, gcp, etc.)
	  - region: Cloud region
	  - availability_zone: Availability zone
	  - short_name: Short cluster name (typically 2 chars)
	  - public_keys: List of SSH public keys
	  - nid_length: Expected length of node IDs

	From SMD Component (node-specific):
	  - hostname: Node hostname from SMD
	  - instance_id: Instance identifier
	  - nid: Numeric node ID
	  - role: Node role (compute, login, storage, etc.)

	From Group.Spec.MetaData (group-specific):
	  - Custom variables defined at group creation/update time

The Pongo2 template engine is compatible with Jinja2 syntax, supporting:
  - Variable substitution: {{ variable_name }}
  - Filters: {{ variable | filter }}
  - Control structures: {% if %}, {% for %}, etc.
  - Built-in functions: range, length, etc.

# Example Template

A typical compute group template might look like:

	#cloud-config
	hostname: {{ hostname }}
	fqdn: {{ hostname }}.{{ cluster_name }}.hpc
	users:
	  - name: root
	    ssh_authorized_keys:
	      {% for key in public_keys %}
	      - {{ key }}
	      {% endfor %}
	packages:
	  - slurm
	  - libfabric
	runcmd:
	  - systemctl enable slurmd
	  - systemctl start slurmd

# Template Validation

When a Group is created or updated, the template is validated:

1. Template syntax validation: Check for valid Jinja2 syntax
2. Variable extraction: Parse {{ }} references from template
3. Sample rendering: Render with sample cluster defaults + mock SMD component
4. YAML validation: Ensure rendered output is valid YAML
5. Version tracking: Generate SHA256 hash and store in TemplateHistory

Benefits of validation at creation time:
  - Errors detected immediately, not at deployment time
  - Invalid templates rejected before reaching production
  - Clear error messages help users fix issues quickly
  - Prevents runtime failures when nodes boot

If validation fails, Status.ValidationError contains details to help debugging.

# Versioning

The Group resource tracks template versions in Status.TemplateHistory:

  - Stores last 10 template versions
  - Each entry contains:
  - Version ID: SHA256 hash of template content
  - Timestamp: When version was created
  - ValidationStatus: Whether version validates
  - ValidationError: Error message if validation failed

This enables rolling back to previous templates if needed and auditing template changes.

# Group Membership

Group membership is determined by the SMD system. When a node requests /{group}.yaml:

1. Handler resolves node IP to SMD component ID
2. Handler queries SMD for groups node belongs to
3. If group is in node's group list, template is rendered and returned
4. If group is not in node's list, 404 Not Found is returned

This authorization model enables role-based configuration:
  - Compute nodes only receive compute group configuration
  - Login nodes only receive login group configuration
  - Storage nodes only receive storage group configuration

# Custom Metadata

Groups can define custom metadata that becomes available as template variables:

	{
	  "spec": {
	    "template": "{{ custom_var }}",
	    "metaData": {
	      "custom_var": "value",
	      "another_var": "another value"
	    }
	  }
	}

Custom metadata enables group-specific customization without modifying templates.
Examples: environment variables, package versions, service configurations.

# Example Workflow

 1. Create group with Jinja2 template and custom metadata:
    POST /groups
    {
    "name": "compute",
    "template": "#cloud-config\npackages:\n  - {{ packages | join(', ') }}",
    "metaData": {"packages": ["gcc", "mpi"]}
    }

2. System validates template:

  - Renders with sample data

  - Confirms output is valid YAML

  - Generates version hash

  - Stores in TemplateHistory

    3. Node boots and requests configuration:
    GET /{group}.yaml (e.g., /compute.yaml)
    With X-Forwarded-For: 10.0.0.100

4. Handler:
  - Resolves IP to component ID (e.g., x1000c0s0b0n0)
  - Checks node's SMD group membership
  - Renders template with node-specific variables
  - Returns rendered YAML to node

# Best Practices

1. Keep templates simple and focused on configuration management
2. Use custom metadata for group-specific values rather than hardcoding
3. Leverage filters for formatting and manipulation
4. Test templates locally with different variable combinations
5. Use meaningful variable names that are self-documenting
6. Include comments in templates for complex logic
7. Avoid sensitive data in templates; use separate secrets mechanisms

# Troubleshooting

Common template issues:

  - Undefined variables: Ensure all referenced variables are in template context
  - Invalid YAML: Check for proper indentation and syntax after rendering
  - Jinja2 syntax errors: Verify filter names and control structure syntax
  - Missing groups in membership: Verify node group membership in SMD

Use Status.ValidationError to identify validation issues at creation time.
Use server logs to debug rendering errors when nodes request configuration.

See examples/ directory for sample templates and complete working examples.
*/
package group
