version = 1
SPDX-PackageName = "OpenCHAMI Metadata Service"
SPDX-PackageSupplier = "OpenCHAMI <info@openchami.org>"
SPDX-PackageDownloadLocation = "https://github.com/openchami/metadata-service"

[[annotations]]
path = [
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "© 2026 OpenCHAMI a Series of LF Projects, LLC"
SPDX-License-Identifier = "MIT"
