// Code generated by fabrica generate. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides storage convenience functions for your resources.
// It uses the fabrica storage backend system.
//
// To modify storage behavior:
//  1. Edit pkg/codegen/templates/storage.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//
// To change storage backend:
//  1. Call storage.Init() with a different backend in main.go
//  2. Options: FileBackend, EntBackend (database), or custom backend
package storage

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/openchami/fabrica/pkg/reconcile"
	fabricaStorage "github.com/openchami/fabrica/pkg/storage"

	"github.com/OpenCHAMI/cloud-init/pkg/resources/clusterdefaults"
	"github.com/OpenCHAMI/cloud-init/pkg/resources/group"
	"github.com/OpenCHAMI/cloud-init/pkg/resources/instanceinfo"
	"github.com/OpenCHAMI/cloud-init/pkg/resources/wireguardpeer"
)

// Backend is the storage backend used by all storage operations.
// Initialize this in your main.go before using any storage functions.
//
// Example:
//
//	backend, err := fabricaStorage.NewFileBackend("./data")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	storage.Init(backend)
var Backend fabricaStorage.StorageBackend

// Init initializes the storage backend.
// This must be called before using any storage functions.
func Init(backend fabricaStorage.StorageBackend) {
	Backend = backend
}

// InitFileBackend is a convenience function to initialize file-based storage.
// It creates the directory if it doesn't exist.
func InitFileBackend(dataDir string) error {
	backend, err := fabricaStorage.NewFileBackend(dataDir)
	if err != nil {
		return fmt.Errorf("failed to create file backend: %w", err)
	}
	Backend = backend
	return nil
}

// ensureBackend panics if Backend is not initialized.
// This is called by all storage functions to ensure proper initialization.
func ensureBackend() {
	if Backend == nil {
		panic("storage backend not initialized: call storage.Init() or storage.InitFileBackend() in main.go")
	}
}

// ClusterDefaults storage operations

// LoadAllClusterDefaultss retrieves all ClusterDefaults resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*clusterdefaults.ClusterDefaults: Slice of ClusterDefaults resources
//   - error: Any error that occurred during loading
func LoadAllClusterDefaultss(ctx context.Context) ([]*clusterdefaults.ClusterDefaults, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "ClusterDefaults")
	if err != nil {
		return nil, fmt.Errorf("failed to load all clusterdefaultss: %w", err)
	}

	clusterdefaultss := make([]*clusterdefaults.ClusterDefaults, 0, len(rawData))
	for _, raw := range rawData {
		clusterDefaults := &clusterdefaults.ClusterDefaults{}
		if err := json.Unmarshal(raw, clusterDefaults); err != nil {
			return nil, fmt.Errorf("failed to unmarshal ClusterDefaults: %w", err)
		}
		clusterdefaultss = append(clusterdefaultss, clusterDefaults)
	}

	return clusterdefaultss, nil
}

// LoadClusterDefaults retrieves a single ClusterDefaults resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the ClusterDefaults resource
//
// Returns:
//   - *clusterdefaults.ClusterDefaults: The ClusterDefaults resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadClusterDefaults(ctx context.Context, uid string) (*clusterdefaults.ClusterDefaults, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "ClusterDefaults", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load ClusterDefaults %s: %w", uid, err)
	}

	clusterDefaults := &clusterdefaults.ClusterDefaults{}
	if err := json.Unmarshal(rawData, clusterDefaults); err != nil {
		return nil, fmt.Errorf("failed to unmarshal ClusterDefaults: %w", err)
	}

	return clusterDefaults, nil
}

// SaveClusterDefaults stores a ClusterDefaults resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - clusterDefaults: The ClusterDefaults resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveClusterDefaults(ctx context.Context, clusterDefaults *clusterdefaults.ClusterDefaults) error {
	ensureBackend()

	data, err := json.Marshal(clusterDefaults)
	if err != nil {
		return fmt.Errorf("failed to marshal ClusterDefaults: %w", err)
	}

	if err := Backend.Save(ctx, "ClusterDefaults", clusterDefaults.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save ClusterDefaults: %w", err)
	}

	return nil
}

// UpdateClusterDefaults updates an existing ClusterDefaults resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - clusterDefaults: The ClusterDefaults resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateClusterDefaults(ctx context.Context, clusterDefaults *clusterdefaults.ClusterDefaults) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "ClusterDefaults", clusterDefaults.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check ClusterDefaults existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(clusterDefaults)
	if err != nil {
		return fmt.Errorf("failed to marshal ClusterDefaults: %w", err)
	}

	if err := Backend.Save(ctx, "ClusterDefaults", clusterDefaults.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update ClusterDefaults: %w", err)
	}

	return nil
}

// DeleteClusterDefaults removes a ClusterDefaults resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the ClusterDefaults resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteClusterDefaults(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "ClusterDefaults", uid); err != nil {
		return fmt.Errorf("failed to delete ClusterDefaults %s: %w", uid, err)
	}

	return nil
}

// ExistsClusterDefaults checks if a ClusterDefaults resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the ClusterDefaults resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsClusterDefaults(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "ClusterDefaults", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check ClusterDefaults existence: %w", err)
	}

	return exists, nil
}

// ListClusterDefaultsUIDs returns UIDs of all ClusterDefaults resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of ClusterDefaults resource UIDs
//   - error: Any error that occurred during listing
func ListClusterDefaultsUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "ClusterDefaults")
	if err != nil {
		return nil, fmt.Errorf("failed to list ClusterDefaults UIDs: %w", err)
	}

	return uids, nil
}

// Group storage operations

// LoadAllGroups retrieves all Group resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*group.Group: Slice of Group resources
//   - error: Any error that occurred during loading
func LoadAllGroups(ctx context.Context) ([]*group.Group, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "Group")
	if err != nil {
		return nil, fmt.Errorf("failed to load all groups: %w", err)
	}

	groups := make([]*group.Group, 0, len(rawData))
	for _, raw := range rawData {
		group := &group.Group{}
		if err := json.Unmarshal(raw, group); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Group: %w", err)
		}
		groups = append(groups, group)
	}

	return groups, nil
}

// LoadGroup retrieves a single Group resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the Group resource
//
// Returns:
//   - *group.Group: The Group resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadGroup(ctx context.Context, uid string) (*group.Group, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "Group", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load Group %s: %w", uid, err)
	}

	group := &group.Group{}
	if err := json.Unmarshal(rawData, group); err != nil {
		return nil, fmt.Errorf("failed to unmarshal Group: %w", err)
	}

	return group, nil
}

// SaveGroup stores a Group resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - group: The Group resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveGroup(ctx context.Context, group *group.Group) error {
	ensureBackend()

	data, err := json.Marshal(group)
	if err != nil {
		return fmt.Errorf("failed to marshal Group: %w", err)
	}

	if err := Backend.Save(ctx, "Group", group.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save Group: %w", err)
	}

	return nil
}

// UpdateGroup updates an existing Group resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - group: The Group resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateGroup(ctx context.Context, group *group.Group) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "Group", group.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check Group existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(group)
	if err != nil {
		return fmt.Errorf("failed to marshal Group: %w", err)
	}

	if err := Backend.Save(ctx, "Group", group.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update Group: %w", err)
	}

	return nil
}

// DeleteGroup removes a Group resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the Group resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteGroup(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "Group", uid); err != nil {
		return fmt.Errorf("failed to delete Group %s: %w", uid, err)
	}

	return nil
}

// ExistsGroup checks if a Group resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the Group resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsGroup(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "Group", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check Group existence: %w", err)
	}

	return exists, nil
}

// ListGroupUIDs returns UIDs of all Group resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of Group resource UIDs
//   - error: Any error that occurred during listing
func ListGroupUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "Group")
	if err != nil {
		return nil, fmt.Errorf("failed to list Group UIDs: %w", err)
	}

	return uids, nil
}

// InstanceInfo storage operations

// LoadAllInstanceInfos retrieves all InstanceInfo resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*instanceinfo.InstanceInfo: Slice of InstanceInfo resources
//   - error: Any error that occurred during loading
func LoadAllInstanceInfos(ctx context.Context) ([]*instanceinfo.InstanceInfo, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "InstanceInfo")
	if err != nil {
		return nil, fmt.Errorf("failed to load all instanceinfos: %w", err)
	}

	instanceinfos := make([]*instanceinfo.InstanceInfo, 0, len(rawData))
	for _, raw := range rawData {
		instanceInfo := &instanceinfo.InstanceInfo{}
		if err := json.Unmarshal(raw, instanceInfo); err != nil {
			return nil, fmt.Errorf("failed to unmarshal InstanceInfo: %w", err)
		}
		instanceinfos = append(instanceinfos, instanceInfo)
	}

	return instanceinfos, nil
}

// LoadInstanceInfo retrieves a single InstanceInfo resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the InstanceInfo resource
//
// Returns:
//   - *instanceinfo.InstanceInfo: The InstanceInfo resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadInstanceInfo(ctx context.Context, uid string) (*instanceinfo.InstanceInfo, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "InstanceInfo", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load InstanceInfo %s: %w", uid, err)
	}

	instanceInfo := &instanceinfo.InstanceInfo{}
	if err := json.Unmarshal(rawData, instanceInfo); err != nil {
		return nil, fmt.Errorf("failed to unmarshal InstanceInfo: %w", err)
	}

	return instanceInfo, nil
}

// SaveInstanceInfo stores a InstanceInfo resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - instanceInfo: The InstanceInfo resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveInstanceInfo(ctx context.Context, instanceInfo *instanceinfo.InstanceInfo) error {
	ensureBackend()

	data, err := json.Marshal(instanceInfo)
	if err != nil {
		return fmt.Errorf("failed to marshal InstanceInfo: %w", err)
	}

	if err := Backend.Save(ctx, "InstanceInfo", instanceInfo.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save InstanceInfo: %w", err)
	}

	return nil
}

// UpdateInstanceInfo updates an existing InstanceInfo resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - instanceInfo: The InstanceInfo resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateInstanceInfo(ctx context.Context, instanceInfo *instanceinfo.InstanceInfo) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "InstanceInfo", instanceInfo.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check InstanceInfo existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(instanceInfo)
	if err != nil {
		return fmt.Errorf("failed to marshal InstanceInfo: %w", err)
	}

	if err := Backend.Save(ctx, "InstanceInfo", instanceInfo.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update InstanceInfo: %w", err)
	}

	return nil
}

// DeleteInstanceInfo removes a InstanceInfo resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the InstanceInfo resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteInstanceInfo(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "InstanceInfo", uid); err != nil {
		return fmt.Errorf("failed to delete InstanceInfo %s: %w", uid, err)
	}

	return nil
}

// ExistsInstanceInfo checks if a InstanceInfo resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the InstanceInfo resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsInstanceInfo(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "InstanceInfo", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check InstanceInfo existence: %w", err)
	}

	return exists, nil
}

// ListInstanceInfoUIDs returns UIDs of all InstanceInfo resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of InstanceInfo resource UIDs
//   - error: Any error that occurred during listing
func ListInstanceInfoUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "InstanceInfo")
	if err != nil {
		return nil, fmt.Errorf("failed to list InstanceInfo UIDs: %w", err)
	}

	return uids, nil
}

// WireGuardPeer storage operations

// LoadAllWireGuardPeers retrieves all WireGuardPeer resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*wireguardpeer.WireGuardPeer: Slice of WireGuardPeer resources
//   - error: Any error that occurred during loading
func LoadAllWireGuardPeers(ctx context.Context) ([]*wireguardpeer.WireGuardPeer, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "WireGuardPeer")
	if err != nil {
		return nil, fmt.Errorf("failed to load all wireguardpeers: %w", err)
	}

	wireguardpeers := make([]*wireguardpeer.WireGuardPeer, 0, len(rawData))
	for _, raw := range rawData {
		wireGuardPeer := &wireguardpeer.WireGuardPeer{}
		if err := json.Unmarshal(raw, wireGuardPeer); err != nil {
			return nil, fmt.Errorf("failed to unmarshal WireGuardPeer: %w", err)
		}
		wireguardpeers = append(wireguardpeers, wireGuardPeer)
	}

	return wireguardpeers, nil
}

// LoadWireGuardPeer retrieves a single WireGuardPeer resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the WireGuardPeer resource
//
// Returns:
//   - *wireguardpeer.WireGuardPeer: The WireGuardPeer resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadWireGuardPeer(ctx context.Context, uid string) (*wireguardpeer.WireGuardPeer, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "WireGuardPeer", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load WireGuardPeer %s: %w", uid, err)
	}

	wireGuardPeer := &wireguardpeer.WireGuardPeer{}
	if err := json.Unmarshal(rawData, wireGuardPeer); err != nil {
		return nil, fmt.Errorf("failed to unmarshal WireGuardPeer: %w", err)
	}

	return wireGuardPeer, nil
}

// SaveWireGuardPeer stores a WireGuardPeer resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - wireGuardPeer: The WireGuardPeer resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveWireGuardPeer(ctx context.Context, wireGuardPeer *wireguardpeer.WireGuardPeer) error {
	ensureBackend()

	data, err := json.Marshal(wireGuardPeer)
	if err != nil {
		return fmt.Errorf("failed to marshal WireGuardPeer: %w", err)
	}

	if err := Backend.Save(ctx, "WireGuardPeer", wireGuardPeer.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save WireGuardPeer: %w", err)
	}

	return nil
}

// UpdateWireGuardPeer updates an existing WireGuardPeer resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - wireGuardPeer: The WireGuardPeer resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateWireGuardPeer(ctx context.Context, wireGuardPeer *wireguardpeer.WireGuardPeer) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "WireGuardPeer", wireGuardPeer.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check WireGuardPeer existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(wireGuardPeer)
	if err != nil {
		return fmt.Errorf("failed to marshal WireGuardPeer: %w", err)
	}

	if err := Backend.Save(ctx, "WireGuardPeer", wireGuardPeer.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update WireGuardPeer: %w", err)
	}

	return nil
}

// DeleteWireGuardPeer removes a WireGuardPeer resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the WireGuardPeer resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteWireGuardPeer(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "WireGuardPeer", uid); err != nil {
		return fmt.Errorf("failed to delete WireGuardPeer %s: %w", uid, err)
	}

	return nil
}

// ExistsWireGuardPeer checks if a WireGuardPeer resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the WireGuardPeer resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsWireGuardPeer(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "WireGuardPeer", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check WireGuardPeer existence: %w", err)
	}

	return exists, nil
}

// ListWireGuardPeerUIDs returns UIDs of all WireGuardPeer resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of WireGuardPeer resource UIDs
//   - error: Any error that occurred during listing
func ListWireGuardPeerUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "WireGuardPeer")
	if err != nil {
		return nil, fmt.Errorf("failed to list WireGuardPeer UIDs: %w", err)
	}

	return uids, nil
}

// StorageClient wraps a StorageBackend to implement reconcile.ClientInterface.
//
// This adapter allows reconcilers to use the storage backend through a
// standard interface that provides typed resource access.
type StorageClient struct {
	backend fabricaStorage.StorageBackend
}

// Compile-time check that StorageClient implements reconcile.ClientInterface
var _ reconcile.ClientInterface = (*StorageClient)(nil)

// NewStorageClient creates a new storage client that wraps the configured backend.
//
// This is used by the reconciliation system to provide reconcilers with
// access to resource storage.
//
// Returns:
//   - *StorageClient: Client that implements reconcile.ClientInterface
func NewStorageClient() *StorageClient {
	ensureBackend()
	return &StorageClient{backend: Backend}
}

// Get retrieves a resource by kind and UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind (e.g., "Device", "Rack")
//   - uid: Unique identifier
//
// Returns:
//   - interface{}: The resource (type-specific)
//   - error: Any error that occurred
func (c *StorageClient) Get(ctx context.Context, kind, uid string) (interface{}, error) {
	rawData, err := c.backend.Load(ctx, kind, uid)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "ClusterDefaults":
		var resource clusterdefaults.ClusterDefaults
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal ClusterDefaults: %w", err)
		}
		return &resource, nil
	case "Group":
		var resource group.Group
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Group: %w", err)
		}
		return &resource, nil
	case "InstanceInfo":
		var resource instanceinfo.InstanceInfo
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal InstanceInfo: %w", err)
		}
		return &resource, nil
	case "WireGuardPeer":
		var resource wireguardpeer.WireGuardPeer
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal WireGuardPeer: %w", err)
		}
		return &resource, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

// List retrieves all resources of a given kind.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind (e.g., "Device", "Rack")
//
// Returns:
//   - []interface{}: Slice of resources
//   - error: Any error that occurred
func (c *StorageClient) List(ctx context.Context, kind string) ([]interface{}, error) {
	rawData, err := c.backend.LoadAll(ctx, kind)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "ClusterDefaults":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource clusterdefaults.ClusterDefaults
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal ClusterDefaults: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "Group":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource group.Group
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal Group: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "InstanceInfo":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource instanceinfo.InstanceInfo
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal InstanceInfo: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "WireGuardPeer":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource wireguardpeer.WireGuardPeer
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal WireGuardPeer: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

// Update updates an existing resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - resource: The resource to update
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Update(ctx context.Context, resource interface{}) error {
	data, err := json.Marshal(resource)
	if err != nil {
		return fmt.Errorf("failed to marshal resource: %w", err)
	}

	// Extract kind and UID based on type
	switch res := resource.(type) {
	case *clusterdefaults.ClusterDefaults:
		return c.backend.Save(ctx, "ClusterDefaults", res.Metadata.UID, data)
	case *group.Group:
		return c.backend.Save(ctx, "Group", res.Metadata.UID, data)
	case *instanceinfo.InstanceInfo:
		return c.backend.Save(ctx, "InstanceInfo", res.Metadata.UID, data)
	case *wireguardpeer.WireGuardPeer:
		return c.backend.Save(ctx, "WireGuardPeer", res.Metadata.UID, data)
	default:
		return fmt.Errorf("unknown resource type: %T", resource)
	}
}

// Create creates a new resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - resource: The resource to create
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Create(ctx context.Context, resource interface{}) error {
	// For storage backend, Create is the same as Update (Save handles both)
	return c.Update(ctx, resource)
}

// Delete deletes a resource by kind and UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind
//   - uid: Unique identifier
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Delete(ctx context.Context, kind, uid string) error {
	return c.backend.Delete(ctx, kind, uid)
}
