// SPDX-FileCopyrightText: © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

// Code generated by Fabrica. DO NOT EDIT manually.
// This is a stub file created during init to prevent import errors.
// It will be replaced when you run 'fabrica generate --storage'

// Package storage handles pluggable storage
package storage

// Placeholder to prevent import errors - will be replaced by generated code
