// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2025 OpenCHAMI Contributors

/*
Package resources contains Fabrica registration glue for the cloud-init metadata service.

Authoritative resource type definitions live under:

	apis/cloud-init.openchami.io/v1/

This package should not define long-lived resource models. It exists primarily for
resource registration and generation compatibility helpers.

# Source of Truth

The service manages these primary resource types in the `apis/.../v1` package:

  - Group
  - ClusterDefaults
  - InstanceInfo
  - WireGuardPeer

# Generated Code

The Fabrica framework automatically generates the following files from these resource
definitions. These files should NOT be manually edited:

  - {resource}_handlers_generated.go: REST API handlers for CRUD operations
  - models_generated.go: Request/response structures
  - routes_generated.go: HTTP route definitions
  - register_generated.go: Resource registration with the Fabrica system

To regenerate after modifying resource definitions in `apis/.../v1`:

	fabrica generate

# Custom Validation

Resource-specific validation logic is implemented directly on resource types in
`apis/cloud-init.openchami.io/v1`.

# REST API Endpoints

The Fabrica framework generates REST API endpoints for each resource type:

	Group Resource:
	  - POST /groups: Create a new group
	  - GET /groups: List all groups
	  - GET /groups/{id}: Get group details
	  - PATCH /groups/{id}: Update group
	  - DELETE /groups/{id}: Delete group

	ClusterDefaults Resource:
	  - POST /clusterdefaults: Create cluster defaults
	  - GET /clusterdefaults: List cluster defaults
	  - GET /clusterdefaults/{id}: Get defaults
	  - PATCH /clusterdefaults/{id}: Update defaults
	  - DELETE /clusterdefaults/{id}: Delete defaults

	InstanceInfo Resource:
	  - POST /instanceinfo: Create instance info
	  - GET /instanceinfo: List instance infos
	  - GET /instanceinfo/{id}: Get instance info
	  - PATCH /instanceinfo/{id}: Update instance info
	  - DELETE /instanceinfo/{id}: Delete instance info

# Resource Identification

Resources are identified by a unique ID (UID) generated by the storage system. This ID
is used in REST API paths and returned in responses. The resource name field is separate
from the UID and can be used for logical identification but is not the primary key.

# Storage

Resources are persisted as JSON files in the data directory:

	./data/Group/*.json: Group configurations
	./data/ClusterDefaults/*.json: Cluster-wide defaults
	./data/InstanceInfo/*.json: Instance-specific overrides

Each resource file contains the complete resource definition including:
  - Metadata (name, UID, creation/update timestamps)
  - Spec: The actual resource configuration
  - Status: Current state including validation results and version history

The storage system automatically handles serialization, deserialization, and concurrent
access management.

# Extending Resources

To add or modify a resource:

1. Edit the resource struct in `apis/cloud-init.openchami.io/v1/*_types.go`
2. Implement or update `Validate()` on that type as needed
3. Update `apis.yaml` and `.fabrica.yaml` if adding new resources/features
4. Run `fabrica generate` to regenerate handlers, middleware, storage, and client code
*/
package resources
