// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2025 OpenCHAMI Contributors

/*
Package resources defines the core data models for the cloud-init metadata service.

This package contains the resource type definitions that are used by the Fabrica framework
to auto-generate REST API handlers, storage operations, and client code. Each resource type
is defined in its own subpackage with custom validation logic as needed.

# Resource Types

The service manages three primary resource types:

  - Group: Template-based node group configurations. Each group contains a Jinja2 template
    that produces cloud-init configuration in YAML format. Groups are the primary mechanism
    for defining group-specific configurations that are rendered and returned via
    /{group}.yaml cloud-init endpoints.

  - ClusterDefaults: Cluster-wide default configuration shared across all nodes. Contains
    base URLs, cloud provider information, SSH public keys, and naming conventions that
    are injected into group templates as template variables.

  - InstanceInfo: Per-node instance-specific configuration overrides. Allows customization
    of hostname, SSH keys, and cloud-init URLs on a per-instance basis, overriding
    cluster defaults.

# Generated Code

The Fabrica framework automatically generates the following files from these resource
definitions. These files should NOT be manually edited:

  - {resource}_handlers_generated.go: REST API handlers for CRUD operations
  - models_generated.go: Request/response structures
  - routes_generated.go: HTTP route definitions
  - register_generated.go: Resource registration with the Fabrica system

To regenerate after modifying resource definitions:

	fabrica generate

# Custom Validation

Resource-specific validation logic is implemented in each resource's subpackage:

  - resources/group: Custom validation for Jinja2 template syntax and YAML output
  - resources/clusterdefaults: Validation of cluster configuration
  - resources/instanceinfo: Validation of per-instance overrides

Custom validation follows this pattern:

 1. Implement Validate(ctx context.Context) error method on resource type
 2. Fabrica framework calls Validate() during Create and Update operations
 3. Validation can modify Status fields to track history or version information
 4. Status modifications automatically persist to storage

Example: Group Template Validation

The Group resource implements custom validation that:

 1. Parses the Jinja2 template
 2. Extracts template variable references
 3. Renders template with sample data (cluster defaults + mock SMD component)
 4. Validates rendered output is valid YAML
 5. Tracks template versions with SHA256 hashing
 6. Stores validation errors in Status.ValidationError for client visibility

This ensures templates are syntactically correct before being deployed to production,
preventing runtime failures when nodes request group configurations.

# REST API Endpoints

The Fabrica framework generates REST API endpoints for each resource type:

	Group Resource:
	  - POST /groups: Create a new group
	  - GET /groups: List all groups
	  - GET /groups/{id}: Get group details
	  - PATCH /groups/{id}: Update group
	  - DELETE /groups/{id}: Delete group

	ClusterDefaults Resource:
	  - POST /clusterdefaults: Create cluster defaults
	  - GET /clusterdefaults: List cluster defaults
	  - GET /clusterdefaults/{id}: Get defaults
	  - PATCH /clusterdefaults/{id}: Update defaults
	  - DELETE /clusterdefaults/{id}: Delete defaults

	InstanceInfo Resource:
	  - POST /instanceinfo: Create instance info
	  - GET /instanceinfo: List instance infos
	  - GET /instanceinfo/{id}: Get instance info
	  - PATCH /instanceinfo/{id}: Update instance info
	  - DELETE /instanceinfo/{id}: Delete instance info

# Resource Identification

Resources are identified by a unique ID (UID) generated by the storage system. This ID
is used in REST API paths and returned in responses. The resource name field is separate
from the UID and can be used for logical identification but is not the primary key.

# Storage

Resources are persisted as JSON files in the data directory:

	./data/Group/*.json: Group configurations
	./data/ClusterDefaults/*.json: Cluster-wide defaults
	./data/InstanceInfo/*.json: Instance-specific overrides

Each resource file contains the complete resource definition including:
  - Metadata (name, UID, creation/update timestamps)
  - Spec: The actual resource configuration
  - Status: Current state including validation results and version history

The storage system automatically handles serialization, deserialization, and concurrent
access management.

# Extending Resources

To add or modify a resource:

1. Edit the resource struct in pkg/resources/{type}/{type}.go
2. Implement or update Validate() method if custom validation is needed
3. Update .fabrica.yaml if adding new resources
4. Run fabrica generate to regenerate all handlers and storage code
5. Handlers, storage operations, and client code are automatically updated

See individual resource subpackages for specific implementation details and examples.
*/
package resources
