// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/OpenCHAMI/cloud-init/apis/cloud-init.openchami.io/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.ClusterDefaults{}); err != nil {
		return fmt.Errorf("failed to register ClusterDefaults: %w", err)
	}
	if err := gen.RegisterResource(&v1.Group{}); err != nil {
		return fmt.Errorf("failed to register Group: %w", err)
	}
	if err := gen.RegisterResource(&v1.InstanceInfo{}); err != nil {
		return fmt.Errorf("failed to register InstanceInfo: %w", err)
	}
	if err := gen.RegisterResource(&v1.WireGuardPeer{}); err != nil {
		return fmt.Errorf("failed to register WireGuardPeer: %w", err)
	}

	return nil
}
