// Code generated by Fabrica dev. DO NOT EDIT.
// Template: cmd/fabrica/generate.go:generateVersionedRegistrationCode
// Generated: 2026-04-28T14:53:21Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/openchami/metadata-service/apis/cloud-init.openchami.io/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.ClusterDefaults{}); err != nil {
		return fmt.Errorf("failed to register ClusterDefaults: %w", err)
	}
	if err := gen.RegisterResource(&v1.Group{}); err != nil {
		return fmt.Errorf("failed to register Group: %w", err)
	}
	if err := gen.RegisterResource(&v1.InstanceInfo{}); err != nil {
		return fmt.Errorf("failed to register InstanceInfo: %w", err)
	}
	if err := gen.RegisterResource(&v1.WireGuardPeer{}); err != nil {
		return fmt.Errorf("failed to register WireGuardPeer: %w", err)
	}

	return nil
}
