// Code generated by fabrica codegen init. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/OpenCHAMI/cloud-init/pkg/resources/clusterdefaults"
	"github.com/OpenCHAMI/cloud-init/pkg/resources/group"
	"github.com/OpenCHAMI/cloud-init/pkg/resources/instanceinfo"
	"github.com/openchami/fabrica/pkg/codegen"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica codegen init' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&clusterdefaults.ClusterDefaults{}); err != nil {
		return fmt.Errorf("failed to register ClusterDefaults: %w", err)
	}
	if err := gen.RegisterResource(&group.Group{}); err != nil {
		return fmt.Errorf("failed to register Group: %w", err)
	}
	if err := gen.RegisterResource(&instanceinfo.InstanceInfo{}); err != nil {
		return fmt.Errorf("failed to register InstanceInfo: %w", err)
	}

	return nil
}
