// Code generated by Fabrica 0.4.5 (commit: 0a2be92b1375e82f25979a964bdce30b8f6a8825). DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-05-13T10:50:13Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for InstanceInfo resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /instanceinfos (list all instanceinfos)
//   - GET /instanceinfos/{uid} (get specific InstanceInfo)
//   - POST /instanceinfos (create new InstanceInfo)
//   - PUT /instanceinfos/{uid} (update InstanceInfo spec)
//   - PATCH /instanceinfos/{uid} (patch InstanceInfo spec)
//   - DELETE /instanceinfos/{uid} (delete InstanceInfo)
//   - PUT /instanceinfos/{uid}/status (update InstanceInfo status)
//   - PATCH /instanceinfos/{uid}/status (patch InstanceInfo status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadInstanceInfo*/SaveInstanceInfo*/DeleteInstanceInfo*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadInstanceInfoWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/OpenCHAMI/metadata-service/apis/cloud-init.openchami.io/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/OpenCHAMI/metadata-service/internal/storage"
)

// GetInstanceInfos returns all InstanceInfo resources
func GetInstanceInfos(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	instanceinfos, err := storage.LoadAllInstanceInfos(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load instanceinfos: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, instanceinfos)
}

// GetInstanceInfo returns a specific InstanceInfo resource by UID
func GetInstanceInfo(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("InstanceInfo UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadInstanceInfo() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	instanceInfo, err := storage.LoadInstanceInfo(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("InstanceInfo not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, instanceInfo)
}

// CreateInstanceInfo creates a new InstanceInfo resource
func CreateInstanceInfo(w http.ResponseWriter, r *http.Request) {
	var req CreateInstanceInfoRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("InstanceInfo")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	instanceInfo := &v1.InstanceInfo{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "InstanceInfo",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	instanceInfo.Metadata = req.Metadata
	instanceInfo.Metadata.UID = uid
	now := time.Now()
	instanceInfo.Metadata.CreatedAt = now
	instanceInfo.Metadata.UpdatedAt = now

	// Set labels and annotations
	if instanceInfo.Metadata.Labels == nil {
		instanceInfo.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		instanceInfo.Metadata.Labels[k] = v
	}
	if instanceInfo.Metadata.Annotations == nil {
		instanceInfo.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		instanceInfo.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), instanceInfo); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveInstanceInfo(r.Context(), instanceInfo); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save InstanceInfo: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "InstanceInfo", instanceInfo.Metadata.UID, instanceInfo.Metadata.Name, instanceInfo); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for InstanceInfo %s: %v\n", instanceInfo.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, instanceInfo)
}

// UpdateInstanceInfo updates the spec of an existing InstanceInfo resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //instanceinfos/{uid}/status to update status.
func UpdateInstanceInfo(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("InstanceInfo UID is required"))
		return
	}

	instanceInfo, err := storage.LoadInstanceInfo(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("InstanceInfo not found: %w", err))
		return
	}

	var req UpdateInstanceInfoRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		instanceInfo.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	instanceInfo.Spec = req.AsSpec()

	// Update labels and annotations
	if instanceInfo.Metadata.Labels == nil {
		instanceInfo.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		instanceInfo.Metadata.Labels[k] = v
	}
	if instanceInfo.Metadata.Annotations == nil {
		instanceInfo.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		instanceInfo.Metadata.Annotations[k] = v
	}

	// Update timestamp
	instanceInfo.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), instanceInfo); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveInstanceInfo(r.Context(), instanceInfo); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save InstanceInfo: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": instanceInfo.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "InstanceInfo", instanceInfo.Metadata.UID, instanceInfo.Metadata.Name, instanceInfo, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for InstanceInfo %s: %v\n", instanceInfo.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, instanceInfo)
}

// PatchInstanceInfo patches an existing InstanceInfo resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchInstanceInfo(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("InstanceInfo UID is required"))
		return
	}

	instanceInfo, err := storage.LoadInstanceInfo(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("InstanceInfo not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(instanceInfo.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &instanceInfo.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	instanceInfo.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), instanceInfo); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Save the patched resource
	if err := storage.SaveInstanceInfo(r.Context(), instanceInfo); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched InstanceInfo: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": instanceInfo.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "InstanceInfo", instanceInfo.Metadata.UID, instanceInfo.Metadata.Name, instanceInfo, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for InstanceInfo %s: %v\n", instanceInfo.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, instanceInfo)
}

// UpdateInstanceInfoStatus updates only the status of a InstanceInfo resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateInstanceInfoStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("InstanceInfo UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadInstanceInfo(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("InstanceInfo not found: %w", err))
		return
	}

	var statusUpdate v1.InstanceInfoStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveInstanceInfo(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save InstanceInfo status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "InstanceInfo", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for InstanceInfo %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchInstanceInfoStatus patches only the status of a InstanceInfo resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchInstanceInfoStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("InstanceInfo UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadInstanceInfo(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("InstanceInfo not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveInstanceInfo(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched InstanceInfo status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "InstanceInfo", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for InstanceInfo %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteInstanceInfo deletes a InstanceInfo resource
func DeleteInstanceInfo(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("InstanceInfo UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	instanceInfo, err := storage.LoadInstanceInfo(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("InstanceInfo not found: %w", err))
		return
	}

	if err := storage.DeleteInstanceInfo(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete InstanceInfo: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "InstanceInfo", instanceInfo.Metadata.UID, instanceInfo.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for InstanceInfo %s: %v\n", instanceInfo.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "InstanceInfo deleted successfully",
		UID:     uid,
	})
}
