// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/OpenCHAMI/cloud-init/internal/storage"
	"github.com/OpenCHAMI/cloud-init/pkg/wireguard"
)

// Config holds all configuration for the service
type Config struct {
	// Server Configuration
	Port         int    `mapstructure:"port"`
	Host         string `mapstructure:"host"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	IdleTimeout  int    `mapstructure:"idle_timeout"`

	// Storage Configuration

	DataDir string `mapstructure:"data_dir"`

	// WireGuard Configuration
	WireGuardStateFile string `mapstructure:"wireguard_state_file"`
	WireGuardOnly      bool   `mapstructure:"wireguard_only"`

	// TokenSmith-backed SMD auth configuration
	TokenSmithURL            string `mapstructure:"tokensmith_url"`
	TokenSmithBootstrapToken string `mapstructure:"tokensmith_bootstrap_token"`
	TokenSmithTargetService  string `mapstructure:"tokensmith_target_service"`
	TokenSmithScopes         string `mapstructure:"tokensmith_scopes"`
	TokenSmithRefreshSkewSec int    `mapstructure:"tokensmith_refresh_skew_sec"`

	// Feature Flags

	Debug bool `mapstructure:"debug"`
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Port:         8080,
		Host:         "0.0.0.0",
		ReadTimeout:  15,
		WriteTimeout: 15,
		IdleTimeout:  60,

		DataDir: "./data",

		WireGuardStateFile: "./data/wireguard/state.yaml",
		WireGuardOnly:      false,

		TokenSmithTargetService:  "smd",
		TokenSmithRefreshSkewSec: 120,

		Debug: false,
	}
}

var (
	cfgFile string
	config  *Config
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal(err)
	}
}

var rootCmd = &cobra.Command{
	Use:   "github.com/OpenCHAMI/cloud-init",
	Short: "",
	Long:  `github.com/OpenCHAMI/cloud-init - A Fabrica-generated OpenCHAMI service`,
	RunE:  runServer,
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the github.com/OpenCHAMI/cloud-init server",
	Long:  `Start the github.com/OpenCHAMI/cloud-init HTTP server with the configured options`,
	RunE:  runServer,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.ochami-metadata.yaml)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug logging")

	// Server flags
	serveCmd.Flags().IntP("port", "p", 8080, "Port to listen on")
	serveCmd.Flags().String("host", "0.0.0.0", "Host to bind to")
	serveCmd.Flags().Int("read-timeout", 15, "Read timeout in seconds")
	serveCmd.Flags().Int("write-timeout", 15, "Write timeout in seconds")
	serveCmd.Flags().Int("idle-timeout", 60, "Idle timeout in seconds")

	serveCmd.Flags().String("data-dir", "./data", "Directory for file storage")

	// WireGuard flags
	serveCmd.Flags().String("wireguard-state-file", "./data/wireguard/state.yaml", "Path to WireGuard state file for persistence")
	serveCmd.Flags().Bool("wireguard-only", false, "Restrict access to WireGuard network only")
	serveCmd.Flags().String("tokensmith-url", "", "TokenSmith service URL for dynamic service tokens")
	serveCmd.Flags().String("tokensmith-bootstrap-token", "", "Bootstrap JWT for service token exchange (prefer env var)")
	serveCmd.Flags().String("tokensmith-target-service", "smd", "Target service name for TokenSmith exchange")
	serveCmd.Flags().String("tokensmith-scopes", "", "Comma-separated scopes for TokenSmith service token")
	serveCmd.Flags().Int("tokensmith-refresh-skew-sec", 120, "Seconds before expiry to proactively refresh token")

	// Bind flags to viper
	viper.BindPFlags(serveCmd.Flags())
	viper.BindPFlags(rootCmd.PersistentFlags())
	viper.RegisterAlias("tokensmith_url", "tokensmith-url")
	viper.RegisterAlias("tokensmith_bootstrap_token", "tokensmith-bootstrap-token")
	viper.RegisterAlias("tokensmith_target_service", "tokensmith-target-service")
	viper.RegisterAlias("tokensmith_scopes", "tokensmith-scopes")
	viper.RegisterAlias("tokensmith_refresh_skew_sec", "tokensmith-refresh-skew-sec")

	// Add subcommands
	rootCmd.AddCommand(serveCmd)

	rootCmd.AddCommand(versionCmd)

}

func initConfig() {
	config = DefaultConfig()

	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		// Search for config in home directory
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".ochami-metadata")
	}

	// Environment variables
	viper.SetEnvPrefix("OCHAMI_METADATA")
	viper.AutomaticEnv()

	// Read config file if it exists
	if err := viper.ReadInConfig(); err == nil {
		log.Printf("Using config file: %s", viper.ConfigFileUsed())
	}

	// Unmarshal config
	if err := viper.Unmarshal(config); err != nil {
		log.Fatalf("Unable to decode into config struct: %v", err)
	}

	// Set debug logging
	if config.Debug {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
		log.Println("Debug logging enabled")
	}
}

func runServer(cmd *cobra.Command, args []string) error {
	log.Printf("Starting github.com/OpenCHAMI/cloud-init server...")
	serverCtx, stopRefresh := context.WithCancel(context.Background())
	defer stopRefresh()

	// Initialize storage backend

	if err := storage.InitFileBackend(config.DataDir); err != nil {
		return fmt.Errorf("failed to initialize file storage: %w", err)
	}
	log.Printf("File storage initialized in %s", config.DataDir)

	// Setup router
	r := chi.NewRouter()

	// Add middleware
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)

	if config.Debug {
		r.Mount("/debug", middleware.Profiler())
	}

	// Optional: enable userspace WireGuard controller via env var WIREGUARD_SERVER (e.g., 100.97.0.1/16)
	var wgController *wireguard.Controller
	if wgCIDR := viper.GetString("wireguard_server"); wgCIDR != "" {
		serverIP, network, err := net.ParseCIDR(wgCIDR)
		if err != nil {
			log.Printf("Invalid WIREGUARD_SERVER value: %v", err)
		} else {
			stateFile := viper.GetString("wireguard_state_file")
			controller, err := wireguard.NewController("wg0", serverIP, network, 51820, stateFile)
			if err != nil {
				log.Printf("Failed to initialize WireGuard controller: %v", err)
			} else {
				wgController = controller
				registerWireGuardRoutes(r, controller, nil)
				log.Printf("WireGuard userspace controller enabled on %s", wgCIDR)
				if stateFile != "" {
					log.Printf("WireGuard state persistence enabled at %s", stateFile)
				}
			}
		}
	}

	// Inject WireGuard controller into context for resource reconciliation and enforce optional wireguard-only access
	if wgController != nil {
		r.Use(wireGuardControllerMiddleware(wgController))
		if viper.GetBool("wireguard_only") {
			r.Use(wireGuardOnlyMiddleware(wgController))
		}
	}

	// Register routes - generated by 'fabrica generate'
	stopReconciliation, err := startReconciliationRuntime(serverCtx, wgController)
	if err != nil {
		return err
	}
	defer func() {
		if err := stopReconciliation(); err != nil {
			log.Printf("Failed to stop reconciliation runtime cleanly: %v", err)
		}
	}()

	RegisterGeneratedRoutes(r)
	r.Get("/health", healthHandler)

	// Initialize SMD client and storage adapter
	smdClient, serviceTokenManager, err := initSMDClient(config)
	if err != nil {
		return err
	}
	storeAdapter := NewStorageAdapter()
	if serviceTokenManager != nil {
		go serviceTokenManager.StartAutoRefresh(serverCtx)
	}

	// Re-register WireGuard routes with SMD client once available
	if wgController != nil {
		registerWireGuardRoutes(r, wgController, smdClient)
	}

	// Register cloud-init metadata server routes
	RegisterCloudInitRoutes(r, smdClient, storeAdapter)

	// Create HTTP server
	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)
	server := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  time.Duration(config.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(config.WriteTimeout) * time.Second,
		IdleTimeout:  time.Duration(config.IdleTimeout) * time.Second,
	}

	// Start server in goroutine
	go func() {
		log.Printf("Server starting on %s", addr)

		log.Printf("Storage: file backend in %s", config.DataDir)

		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	stopRefresh()
	log.Println("Server shutting down...")

	// Graceful shutdown with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		return fmt.Errorf("server forced to shutdown: %w", err)
	}

	log.Println("Server exited")
	return nil
}

func parseScopeCSV(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}

	parts := strings.Split(raw, ",")
	scopes := make([]string, 0, len(parts))
	for _, p := range parts {
		s := strings.TrimSpace(p)
		if s != "" {
			scopes = append(scopes, s)
		}
	}

	if len(scopes) == 0 {
		return nil
	}

	return scopes
}

// Health check handler
func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status":"healthy","service":"github.com/OpenCHAMI/cloud-init"}`))
}

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number",
	Long:  `Print the version number of github.com/OpenCHAMI/cloud-init`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("github.com/OpenCHAMI/cloud-init v1.0.0")
	},
}
