// Code generated by Fabrica v0.4.9 (commit: 70cad05). DO NOT EDIT.
// Template: init/metrics_helpers.go.tmpl
// Generated: 2026-07-22T17:03:21Z
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

// initializeMetrics creates and configures the metrics system.
// Returns the metrics instance for use in middleware and the /metrics handler.
func initializeMetrics(config *Config) *Metrics {
	return NewMetrics("main")
}
