// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains OpenAPI 3.0 specification generation for all resources.
// Generated from: pkg/codegen/templates/server/openapi.go.tmpl
//
// To modify OpenAPI spec:
//  1. Edit the template file: pkg/codegen/templates/server/openapi.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// OpenAPI endpoints:
//   - GET /openapi.json - Returns OpenAPI 3.0 spec
//   - GET /docs - Returns Swagger UI
//
// This file automatically generates OpenAPI schemas from Go types using
// kin-openapi's openapi3gen package. No docstring annotations required.
package main

import (
	"encoding/json"
	"net/http"

	"github.com/OpenCHAMI/metadata-service/apis/cloud-init.openchami.io/v1"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
)

// ServeOpenAPISpec returns the OpenAPI 3.0 specification
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	spec := GenerateOpenAPISpec()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(spec); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeSwaggerUI returns the Swagger UI HTML page
func ServeSwaggerUI(w http.ResponseWriter, r *http.Request) {
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>metadata_service API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; padding:0; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "/openapi.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// GenerateOpenAPISpec generates the complete OpenAPI 3.0 specification
func GenerateOpenAPISpec() *openapi3.T {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       "metadata_service API",
			Description: "Fabrica-generated REST API with Kubernetes-style resource management",
			Version:     "1.0.0",
			Contact: &openapi3.Contact{
				Name: "Fabrica Project",
				URL:  "https://github.com/openchami/fabrica",
			},
		},
		Servers: openapi3.Servers{
			{
				URL:         "http://localhost:8080",
				Description: "Development server",
			},
		},
		Paths: openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas: make(openapi3.Schemas),
		},
	}

	// Register all resource paths
	registerClusterDefaultsPaths(spec)
	registerGroupPaths(spec)
	registerInstanceInfoPaths(spec)
	registerWireGuardPeerPaths(spec)

	// Register /health endpoint
	healthOp := openapi3.NewOperation()
	healthOp.OperationID = "health"
	healthOp.Summary = "Service health"
	healthOp.Description = "Returns service health information"
	healthOp.Tags = []string{"Service"}
	healthResponseSchema := openapi3.NewObjectSchema().
		WithProperty("status", openapi3.NewStringSchema()).
		WithProperty("service", openapi3.NewStringSchema()).
		WithProperty("version", openapi3.NewStringSchema()).
		WithProperty("time", openapi3.NewStringSchema()).
		WithRequired([]string{"status"})
	healthExample := map[string]interface{}{
		"status":  "ok",
		"service": "metadata_service",
		"version": "1.0.0",
		"time":    "2026-01-01T00:00:00Z",
	}
	healthResponseSchema.Example = healthExample
	healthOp.Responses = openapi3.NewResponses()
	healthOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Healthy").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: healthResponseSchema},
					Example: healthExample,
				},
			}),
	})
	spec.Paths.Set("/health", &openapi3.PathItem{Get: healthOp})

	// Register /openapi.json endpoint (self-referential spec endpoint)
	openAPIJSONExample := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":   "metadata_service API",
			"version": "1.0.0",
		},
	}
	openAPIJsonOp := openapi3.NewOperation()
	openAPIJsonOp.OperationID = "getOpenAPISpec"
	openAPIJsonOp.Summary = "Get OpenAPI specification"
	openAPIJsonOp.Description = "Returns the complete OpenAPI 3.0 specification for this API"
	openAPIJsonOp.Tags = []string{"Service"}
	openAPIJsonOp.Responses = openapi3.NewResponses()
	openAPIJsonOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("OpenAPI specification").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()},
					Example: openAPIJSONExample,
				},
			}),
	})
	spec.Paths.Set("/openapi.json", &openapi3.PathItem{Get: openAPIJsonOp})

	// Register /docs endpoint (Swagger UI)
	docsOp := openapi3.NewOperation()
	docsOp.OperationID = "getSwaggerUI"
	docsOp.Summary = "API documentation UI"
	docsOp.Description = "Returns an interactive Swagger UI for exploring the API"
	docsOp.Tags = []string{"Service"}
	docsOp.Responses = openapi3.NewResponses()
	docsOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Swagger UI HTML page").
			WithContent(map[string]*openapi3.MediaType{
				"text/html": {
					Schema: &openapi3.SchemaRef{Value: openapi3.NewStringSchema()},
				},
			}),
	})
	spec.Paths.Set("/docs", &openapi3.PathItem{Get: docsOp})

	// Register custom (non-Fabrica-generated) paths.
	// Defined in openapi_extensions.go – safe to edit, never overwritten.
	registerCustomOpenAPIPaths(spec)

	return spec
}

// registerClusterDefaultsPaths registers OpenAPI paths for ClusterDefaults resources
func registerClusterDefaultsPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.ClusterDefaults{}, spec.Components.Schemas)
	spec.Components.Schemas["ClusterDefaults"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateClusterDefaultsRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateClusterDefaultsRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateClusterDefaultsRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateClusterDefaultsRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.ClusterDefaultsStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["ClusterDefaultsStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List ClusterDefaultss operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listClusterDefaultss"
	listOp.Summary = "List all ClusterDefaults resources"
	listOp.Description = "Returns a list of all ClusterDefaults resources in the inventory"
	listOp.Tags = []string{"ClusterDefaults"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/ClusterDefaults"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create ClusterDefaults operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createClusterDefaults"
	createOp.Summary = "Create a new ClusterDefaults resource"
	createOp.Description = "Creates a new ClusterDefaults resource with the provided specification"
	createOp.Tags = []string{"ClusterDefaults"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateClusterDefaultsRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ClusterDefaults",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get ClusterDefaults operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getClusterDefaults"
	getOp.Summary = "Get a specific ClusterDefaults resource"
	getOp.Description = "Returns details of a specific ClusterDefaults resource by UID"
	getOp.Tags = []string{"ClusterDefaults"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ClusterDefaults",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update ClusterDefaults operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateClusterDefaults"
	updateOp.Summary = "Update a ClusterDefaults resource"
	updateOp.Description = "Updates an existing ClusterDefaults resource with new values"
	updateOp.Tags = []string{"ClusterDefaults"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateClusterDefaultsRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ClusterDefaults",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch ClusterDefaults operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchClusterDefaults"
	patchOp.Summary = "Patch a ClusterDefaults resource"
	patchOp.Description = "Partially updates an existing ClusterDefaults resource using patch semantics"
	patchOp.Tags = []string{"ClusterDefaults"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ClusterDefaults",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update ClusterDefaults status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateClusterDefaultsStatus"
	updateStatusOp.Summary = "Update ClusterDefaults status"
	updateStatusOp.Description = "Updates only the status subresource for an existing ClusterDefaults"
	updateStatusOp.Tags = []string{"ClusterDefaults"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ClusterDefaultsStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ClusterDefaults"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch ClusterDefaults status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchClusterDefaultsStatus"
	patchStatusOp.Summary = "Patch ClusterDefaults status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing ClusterDefaults"
	patchStatusOp.Tags = []string{"ClusterDefaults"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ClusterDefaults"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete ClusterDefaults operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteClusterDefaults"
	deleteOp.Summary = "Delete a ClusterDefaults resource"
	deleteOp.Description = "Removes a ClusterDefaults resource from the inventory"
	deleteOp.Tags = []string{"ClusterDefaults"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the ClusterDefaults resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/clusterdefaultss", collectionPath)
	spec.Paths.Set("/clusterdefaultss/{uid}", itemPath)
	spec.Paths.Set("/clusterdefaultss/{uid}/status", statusPath)
}

// registerGroupPaths registers OpenAPI paths for Group resources
func registerGroupPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.Group{}, spec.Components.Schemas)
	spec.Components.Schemas["Group"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateGroupRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateGroupRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateGroupRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateGroupRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.GroupStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["GroupStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List Groups operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listGroups"
	listOp.Summary = "List all Group resources"
	listOp.Description = "Returns a list of all Group resources in the inventory"
	listOp.Tags = []string{"Group"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/Group"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create Group operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createGroup"
	createOp.Summary = "Create a new Group resource"
	createOp.Description = "Creates a new Group resource with the provided specification"
	createOp.Tags = []string{"Group"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateGroupRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get Group operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getGroup"
	getOp.Summary = "Get a specific Group resource"
	getOp.Description = "Returns details of a specific Group resource by UID"
	getOp.Tags = []string{"Group"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update Group operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateGroup"
	updateOp.Summary = "Update a Group resource"
	updateOp.Description = "Updates an existing Group resource with new values"
	updateOp.Tags = []string{"Group"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateGroupRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch Group operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchGroup"
	patchOp.Summary = "Patch a Group resource"
	patchOp.Description = "Partially updates an existing Group resource using patch semantics"
	patchOp.Tags = []string{"Group"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update Group status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateGroupStatus"
	updateStatusOp.Summary = "Update Group status"
	updateStatusOp.Description = "Updates only the status subresource for an existing Group"
	updateStatusOp.Tags = []string{"Group"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/GroupStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Group"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch Group status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchGroupStatus"
	patchStatusOp.Summary = "Patch Group status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing Group"
	patchStatusOp.Tags = []string{"Group"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Group"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete Group operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteGroup"
	deleteOp.Summary = "Delete a Group resource"
	deleteOp.Description = "Removes a Group resource from the inventory"
	deleteOp.Tags = []string{"Group"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the Group resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/groups", collectionPath)
	spec.Paths.Set("/groups/{uid}", itemPath)
	spec.Paths.Set("/groups/{uid}/status", statusPath)
}

// registerInstanceInfoPaths registers OpenAPI paths for InstanceInfo resources
func registerInstanceInfoPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.InstanceInfo{}, spec.Components.Schemas)
	spec.Components.Schemas["InstanceInfo"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateInstanceInfoRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateInstanceInfoRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateInstanceInfoRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateInstanceInfoRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.InstanceInfoStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["InstanceInfoStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List InstanceInfos operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listInstanceInfos"
	listOp.Summary = "List all InstanceInfo resources"
	listOp.Description = "Returns a list of all InstanceInfo resources in the inventory"
	listOp.Tags = []string{"InstanceInfo"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/InstanceInfo"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create InstanceInfo operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createInstanceInfo"
	createOp.Summary = "Create a new InstanceInfo resource"
	createOp.Description = "Creates a new InstanceInfo resource with the provided specification"
	createOp.Tags = []string{"InstanceInfo"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateInstanceInfoRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/InstanceInfo",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get InstanceInfo operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getInstanceInfo"
	getOp.Summary = "Get a specific InstanceInfo resource"
	getOp.Description = "Returns details of a specific InstanceInfo resource by UID"
	getOp.Tags = []string{"InstanceInfo"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/InstanceInfo",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update InstanceInfo operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateInstanceInfo"
	updateOp.Summary = "Update a InstanceInfo resource"
	updateOp.Description = "Updates an existing InstanceInfo resource with new values"
	updateOp.Tags = []string{"InstanceInfo"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateInstanceInfoRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/InstanceInfo",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch InstanceInfo operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchInstanceInfo"
	patchOp.Summary = "Patch a InstanceInfo resource"
	patchOp.Description = "Partially updates an existing InstanceInfo resource using patch semantics"
	patchOp.Tags = []string{"InstanceInfo"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/InstanceInfo",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update InstanceInfo status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateInstanceInfoStatus"
	updateStatusOp.Summary = "Update InstanceInfo status"
	updateStatusOp.Description = "Updates only the status subresource for an existing InstanceInfo"
	updateStatusOp.Tags = []string{"InstanceInfo"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/InstanceInfoStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/InstanceInfo"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch InstanceInfo status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchInstanceInfoStatus"
	patchStatusOp.Summary = "Patch InstanceInfo status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing InstanceInfo"
	patchStatusOp.Tags = []string{"InstanceInfo"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/InstanceInfo"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete InstanceInfo operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteInstanceInfo"
	deleteOp.Summary = "Delete a InstanceInfo resource"
	deleteOp.Description = "Removes a InstanceInfo resource from the inventory"
	deleteOp.Tags = []string{"InstanceInfo"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the InstanceInfo resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/instanceinfos", collectionPath)
	spec.Paths.Set("/instanceinfos/{uid}", itemPath)
	spec.Paths.Set("/instanceinfos/{uid}/status", statusPath)
}

// registerWireGuardPeerPaths registers OpenAPI paths for WireGuardPeer resources
func registerWireGuardPeerPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.WireGuardPeer{}, spec.Components.Schemas)
	spec.Components.Schemas["WireGuardPeer"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateWireGuardPeerRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateWireGuardPeerRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateWireGuardPeerRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateWireGuardPeerRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.WireGuardPeerStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["WireGuardPeerStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List WireGuardPeers operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listWireGuardPeers"
	listOp.Summary = "List all WireGuardPeer resources"
	listOp.Description = "Returns a list of all WireGuardPeer resources in the inventory"
	listOp.Tags = []string{"WireGuardPeer"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/WireGuardPeer"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create WireGuardPeer operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createWireGuardPeer"
	createOp.Summary = "Create a new WireGuardPeer resource"
	createOp.Description = "Creates a new WireGuardPeer resource with the provided specification"
	createOp.Tags = []string{"WireGuardPeer"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateWireGuardPeerRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/WireGuardPeer",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get WireGuardPeer operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getWireGuardPeer"
	getOp.Summary = "Get a specific WireGuardPeer resource"
	getOp.Description = "Returns details of a specific WireGuardPeer resource by UID"
	getOp.Tags = []string{"WireGuardPeer"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/WireGuardPeer",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update WireGuardPeer operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateWireGuardPeer"
	updateOp.Summary = "Update a WireGuardPeer resource"
	updateOp.Description = "Updates an existing WireGuardPeer resource with new values"
	updateOp.Tags = []string{"WireGuardPeer"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateWireGuardPeerRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/WireGuardPeer",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch WireGuardPeer operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchWireGuardPeer"
	patchOp.Summary = "Patch a WireGuardPeer resource"
	patchOp.Description = "Partially updates an existing WireGuardPeer resource using patch semantics"
	patchOp.Tags = []string{"WireGuardPeer"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/WireGuardPeer",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update WireGuardPeer status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateWireGuardPeerStatus"
	updateStatusOp.Summary = "Update WireGuardPeer status"
	updateStatusOp.Description = "Updates only the status subresource for an existing WireGuardPeer"
	updateStatusOp.Tags = []string{"WireGuardPeer"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/WireGuardPeerStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/WireGuardPeer"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch WireGuardPeer status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchWireGuardPeerStatus"
	patchStatusOp.Summary = "Patch WireGuardPeer status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing WireGuardPeer"
	patchStatusOp.Tags = []string{"WireGuardPeer"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/WireGuardPeer"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete WireGuardPeer operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteWireGuardPeer"
	deleteOp.Summary = "Delete a WireGuardPeer resource"
	deleteOp.Description = "Removes a WireGuardPeer resource from the inventory"
	deleteOp.Tags = []string{"WireGuardPeer"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the WireGuardPeer resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/wireguardpeers", collectionPath)
	spec.Paths.Set("/wireguardpeers/{uid}", itemPath)
	spec.Paths.Set("/wireguardpeers/{uid}/status", statusPath)
}

func patchRequestBody() *openapi3.RequestBodyRef {
	patchSchema := &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()}
	return &openapi3.RequestBodyRef{
		Value: &openapi3.RequestBody{
			Required: true,
			Content: openapi3.Content{
				"application/merge-patch+json": &openapi3.MediaType{Schema: patchSchema},
				"application/json-patch+json":  &openapi3.MediaType{Schema: patchSchema},
				"application/shorthand-patch":  &openapi3.MediaType{Schema: patchSchema},
				"application/json":             &openapi3.MediaType{Schema: patchSchema},
			},
		},
	}
}

// Helper function for error responses
func errorResponse() *openapi3.ResponseRef {
	return &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Error response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ErrorResponse",
			}),
	}
}
