// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /clusterdefaultss (ClusterDefaults operations)
//   - /groups (Group operations)
//   - /instanceinfos (InstanceInfo operations)
//   - /wireguardpeers (WireGuardPeer operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"net/http"

	"github.com/OpenCHAMI/cloud-init/internal/authz"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("ClusterDefaults", "clusterdefaults")

	resource.RegisterResourcePrefix("Group", "group")

	resource.RegisterResourcePrefix("InstanceInfo", "instanceinfo")

	resource.RegisterResourcePrefix("WireGuardPeer", "wireguardpeer")

	return nil
}

// RegisterGeneratedRoutes registers all generated routes
// Note: Middleware should be applied in main.go before calling this function
func RegisterGeneratedRoutes(r chi.Router) {

	// ClusterDefaults routes
	r.Route("/clusterdefaultss", func(r chi.Router) {
		r.Method(http.MethodGet, "/", authz.AnnotateRoute(http.MethodGet, "/clusterdefaultss/", authz.Require(authz.ObjectNodeMetadata, authz.ActionRead), http.HandlerFunc(GetClusterDefaultss)))
		r.Method(http.MethodPost, "/", authz.AnnotateRoute(http.MethodPost, "/clusterdefaultss/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(CreateClusterDefaults)))
		r.Route("/{uid}", func(r chi.Router) {
			r.Method(http.MethodGet, "/", authz.AnnotateRoute(http.MethodGet, "/clusterdefaultss/{uid}/", authz.Require(authz.ObjectNodeMetadata, authz.ActionRead), http.HandlerFunc(GetClusterDefaults)))
			r.Method(http.MethodPut, "/", authz.AnnotateRoute(http.MethodPut, "/clusterdefaultss/{uid}/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(UpdateClusterDefaults)))
			r.Method(http.MethodPatch, "/", authz.AnnotateRoute(http.MethodPatch, "/clusterdefaultss/{uid}/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(PatchClusterDefaults)))
			r.Method(http.MethodDelete, "/", authz.AnnotateRoute(http.MethodDelete, "/clusterdefaultss/{uid}/", authz.Require(authz.ObjectNodeMetadata, authz.ActionDelete), http.HandlerFunc(DeleteClusterDefaults)))

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Method(http.MethodPut, "/", authz.AnnotateRoute(http.MethodPut, "/clusterdefaultss/{uid}/status/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(UpdateClusterDefaultsStatus)))
				r.Method(http.MethodPatch, "/", authz.AnnotateRoute(http.MethodPatch, "/clusterdefaultss/{uid}/status/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(PatchClusterDefaultsStatus)))
			})
		})
	})

	// Group routes
	r.Route("/groups", func(r chi.Router) {
		r.Method(http.MethodGet, "/", authz.AnnotateRoute(http.MethodGet, "/groups/", authz.Require(authz.ObjectGroupMetadata, authz.ActionRead), http.HandlerFunc(GetGroups)))
		r.Method(http.MethodPost, "/", authz.AnnotateRoute(http.MethodPost, "/groups/", authz.Require(authz.ObjectGroupMetadata, authz.ActionWrite), http.HandlerFunc(CreateGroup)))
		r.Route("/{uid}", func(r chi.Router) {
			r.Method(http.MethodGet, "/", authz.AnnotateRoute(http.MethodGet, "/groups/{uid}/", authz.Require(authz.ObjectGroupMetadata, authz.ActionRead), http.HandlerFunc(GetGroup)))
			r.Method(http.MethodPut, "/", authz.Require(authz.ObjectGroupMetadata, authz.ActionWrite)(http.HandlerFunc(UpdateGroup)))
			r.Method(http.MethodPatch, "/", authz.Require(authz.ObjectGroupMetadata, authz.ActionWrite)(http.HandlerFunc(PatchGroup)))
			r.Method(http.MethodDelete, "/", authz.AnnotateRoute(http.MethodDelete, "/groups/{uid}/", authz.Require(authz.ObjectGroupMetadata, authz.ActionDelete), http.HandlerFunc(DeleteGroup)))

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Method(http.MethodPut, "/", authz.Require(authz.ObjectGroupMetadata, authz.ActionWrite)(http.HandlerFunc(UpdateGroupStatus)))
				r.Method(http.MethodPatch, "/", authz.Require(authz.ObjectGroupMetadata, authz.ActionWrite)(http.HandlerFunc(PatchGroupStatus)))
			})
		})
	})

	// InstanceInfo routes
	r.Route("/instanceinfos", func(r chi.Router) {
		r.Method(http.MethodGet, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionRead)(http.HandlerFunc(GetInstanceInfos)))
		r.Method(http.MethodPost, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite)(http.HandlerFunc(CreateInstanceInfo)))
		r.Route("/{uid}", func(r chi.Router) {
			r.Method(http.MethodGet, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionRead)(http.HandlerFunc(GetInstanceInfo)))
			r.Method(http.MethodPut, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite)(http.HandlerFunc(UpdateInstanceInfo)))
			r.Method(http.MethodPatch, "/", authz.AnnotateRoute(http.MethodPatch, "/instanceinfos/{uid}/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(PatchInstanceInfo)))
			r.Method(http.MethodDelete, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionDelete)(http.HandlerFunc(DeleteInstanceInfo)))

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Method(http.MethodPut, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite)(http.HandlerFunc(UpdateInstanceInfoStatus)))
				r.Method(http.MethodPatch, "/", authz.AnnotateRoute(http.MethodPatch, "/instanceinfos/{uid}/status/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(PatchInstanceInfoStatus)))
			})
		})
	})

	// WireGuardPeer routes
	r.Route("/wireguardpeers", func(r chi.Router) {
		r.Method(http.MethodGet, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionRead)(http.HandlerFunc(GetWireGuardPeers)))
		r.Method(http.MethodPost, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite)(http.HandlerFunc(CreateWireGuardPeer)))
		r.Route("/{uid}", func(r chi.Router) {
			r.Method(http.MethodGet, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionRead)(http.HandlerFunc(GetWireGuardPeer)))
			r.Method(http.MethodPut, "/", authz.AnnotateRoute(http.MethodPut, "/wireguardpeers/{uid}/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite), http.HandlerFunc(UpdateWireGuardPeer)))
			r.Method(http.MethodPatch, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite)(http.HandlerFunc(PatchWireGuardPeer)))
			r.Method(http.MethodDelete, "/", authz.AnnotateRoute(http.MethodDelete, "/wireguardpeers/{uid}/", authz.Require(authz.ObjectNodeMetadata, authz.ActionDelete), http.HandlerFunc(DeleteWireGuardPeer)))

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Method(http.MethodPut, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite)(http.HandlerFunc(UpdateWireGuardPeerStatus)))
				r.Method(http.MethodPatch, "/", authz.Require(authz.ObjectNodeMetadata, authz.ActionWrite)(http.HandlerFunc(PatchWireGuardPeerStatus)))
			})
		})
	})

	// OpenAPI documentation routes
	r.Method(http.MethodGet, "/openapi.json", authz.Public()(http.HandlerFunc(ServeOpenAPISpec)))
	r.Method(http.MethodGet, "/docs", authz.Public()(http.HandlerFunc(ServeSwaggerUI)))
}
