// Code generated by Fabrica v0.4.9 (commit: 70cad05). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /clusterdefaultss (ClusterDefaults operations)
//   - /groups (Group operations)
//   - /instanceinfos (InstanceInfo operations)
//   - /wireguardpeers (WireGuardPeer operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("ClusterDefaults", "clusterdefaults")

	resource.RegisterResourcePrefix("Group", "group")

	resource.RegisterResourcePrefix("InstanceInfo", "instanceinfo")

	resource.RegisterResourcePrefix("WireGuardPeer", "wireguardpeer")

	return nil
}

// RegisterGeneratedRoutes registers all generated resource routes.
// The router passed to this function should already have middleware applied in main.go.
// Public service routes such as /health, /openapi.json, and /docs are registered
// in cmd/server/main.go so they remain outside auth middleware.
func RegisterGeneratedRoutes(r chi.Router) {
	// Routes inherit middleware from the router passed by main.go

	// ClusterDefaults routes
	r.Route("/clusterdefaultss", func(resource chi.Router) {
		resource.Get("/", GetClusterDefaultss)
		resource.Post("/", CreateClusterDefaults)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetClusterDefaults)
			item.Put("/", UpdateClusterDefaults)
			item.Patch("/", PatchClusterDefaults)
			item.Delete("/", DeleteClusterDefaults)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateClusterDefaultsStatus)
				status.Patch("/", PatchClusterDefaultsStatus)
			})
		})
	})

	// Group routes
	r.Route("/groups", func(resource chi.Router) {
		resource.Get("/", GetGroups)
		resource.Post("/", CreateGroup)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetGroup)
			item.Put("/", UpdateGroup)
			item.Patch("/", PatchGroup)
			item.Delete("/", DeleteGroup)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateGroupStatus)
				status.Patch("/", PatchGroupStatus)
			})
		})
	})

	// InstanceInfo routes
	r.Route("/instanceinfos", func(resource chi.Router) {
		resource.Get("/", GetInstanceInfos)
		resource.Post("/", CreateInstanceInfo)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetInstanceInfo)
			item.Put("/", UpdateInstanceInfo)
			item.Patch("/", PatchInstanceInfo)
			item.Delete("/", DeleteInstanceInfo)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateInstanceInfoStatus)
				status.Patch("/", PatchInstanceInfoStatus)
			})
		})
	})

	// WireGuardPeer routes
	r.Route("/wireguardpeers", func(resource chi.Router) {
		resource.Get("/", GetWireGuardPeers)
		resource.Post("/", CreateWireGuardPeer)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetWireGuardPeer)
			item.Put("/", UpdateWireGuardPeer)
			item.Patch("/", PatchWireGuardPeer)
			item.Delete("/", DeleteWireGuardPeer)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateWireGuardPeerStatus)
				status.Patch("/", PatchWireGuardPeerStatus)
			})
		})
	})

}
