// Code generated by Fabrica 0.3.0. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for WireGuardPeer resources.
// Generated from: pkg/codegen/templates/handlers.go.tmpl
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /wireguardpeers (list all wireguardpeers)
//   - GET /wireguardpeers/{uid} (get specific WireGuardPeer)
//   - POST /wireguardpeers (create new WireGuardPeer)
//   - PUT /wireguardpeers/{uid} (update WireGuardPeer spec)
//   - PATCH /wireguardpeers/{uid} (patch WireGuardPeer spec)
//   - DELETE /wireguardpeers/{uid} (delete WireGuardPeer)
//   - PUT /wireguardpeers/{uid}/status (update WireGuardPeer status)
//   - PATCH /wireguardpeers/{uid}/status (patch WireGuardPeer status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadWireGuardPeer*/SaveWireGuardPeer*/DeleteWireGuardPeer*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/wireguardpeer/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadWireGuardPeerWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/OpenCHAMI/cloud-init/internal/storage"
	"github.com/OpenCHAMI/cloud-init/pkg/resources/wireguardpeer"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
)

// GetWireGuardPeers returns all WireGuardPeer resources
func GetWireGuardPeers(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	wireguardpeers, err := storage.LoadAllWireGuardPeers(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load wireguardpeers: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, wireguardpeers)
}

// GetWireGuardPeer returns a specific WireGuardPeer resource by UID
func GetWireGuardPeer(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("WireGuardPeer UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadWireGuardPeer() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	wireGuardPeer, err := storage.LoadWireGuardPeer(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("WireGuardPeer not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, wireGuardPeer)
}

// CreateWireGuardPeer creates a new WireGuardPeer resource
func CreateWireGuardPeer(w http.ResponseWriter, r *http.Request) {
	var req CreateWireGuardPeerRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("WireGuardPeer")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	wireGuardPeer := &wireguardpeer.WireGuardPeer{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "WireGuardPeer",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.WireGuardPeerSpec,
	}

	wireGuardPeer.Metadata.Initialize(req.Name, uid)

	// Set labels and annotations
	for k, v := range req.Labels {
		wireGuardPeer.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		wireGuardPeer.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(wireGuardPeer); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), wireGuardPeer); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveWireGuardPeer(r.Context(), wireGuardPeer); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save WireGuardPeer: %w", err))
		return
	}

	if err := reconcileWireGuardPeer(r.Context(), wireGuardPeer); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to reconcile WireGuardPeer: %w", err))
		return
	}

	// Publish resource created event
	if err := events.PublishResourceCreated(r.Context(), "WireGuardPeer", wireGuardPeer.GetUID(), wireGuardPeer.GetName(), wireGuardPeer); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for WireGuardPeer %s: %v\n", wireGuardPeer.GetUID(), err)
	}

	respondJSON(w, http.StatusCreated, wireGuardPeer)
}

// UpdateWireGuardPeer updates the spec of an existing WireGuardPeer resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //wireguardpeers/{uid}/status to update status.
func UpdateWireGuardPeer(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("WireGuardPeer UID is required"))
		return
	}

	wireGuardPeer, err := storage.LoadWireGuardPeer(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("WireGuardPeer not found: %w", err))
		return
	}

	var req UpdateWireGuardPeerRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		wireGuardPeer.SetName(req.Name)
	}

	// Update spec fields ONLY - status should use /status subresource
	wireGuardPeer.Spec = req.WireGuardPeerSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		wireGuardPeer.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		wireGuardPeer.SetAnnotation(k, v)
	}

	wireGuardPeer.Touch()

	if err := storage.SaveWireGuardPeer(r.Context(), wireGuardPeer); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save WireGuardPeer: %w", err))
		return
	}

	if err := reconcileWireGuardPeer(r.Context(), wireGuardPeer); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to reconcile WireGuardPeer: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": wireGuardPeer.Metadata.UpdatedAt,
	}
	if err := events.PublishResourceUpdated(r.Context(), "WireGuardPeer", wireGuardPeer.GetUID(), wireGuardPeer.GetName(), wireGuardPeer, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for WireGuardPeer %s: %v\n", wireGuardPeer.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, wireGuardPeer)
}

// PatchWireGuardPeer patches an existing WireGuardPeer resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchWireGuardPeer(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("WireGuardPeer UID is required"))
		return
	}

	wireGuardPeer, err := storage.LoadWireGuardPeer(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("WireGuardPeer not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(wireGuardPeer.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &wireGuardPeer.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata
	wireGuardPeer.Touch()

	// Save the patched resource
	if err := storage.SaveWireGuardPeer(r.Context(), wireGuardPeer); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched WireGuardPeer: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": wireGuardPeer.Metadata.UpdatedAt,
	}
	if err := events.PublishResourcePatched(r.Context(), "WireGuardPeer", wireGuardPeer.GetUID(), wireGuardPeer.GetName(), wireGuardPeer, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for WireGuardPeer %s: %v\n", wireGuardPeer.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, wireGuardPeer)
}

// UpdateWireGuardPeerStatus updates only the status of a WireGuardPeer resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateWireGuardPeerStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("WireGuardPeer UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadWireGuardPeer(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("WireGuardPeer not found: %w", err))
		return
	}

	var statusUpdate wireguardpeer.WireGuardPeerStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate
	res.Touch()

	if err := storage.SaveWireGuardPeer(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save WireGuardPeer status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourceUpdated(r.Context(), "WireGuardPeer", res.GetUID(), res.GetName(), res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for WireGuardPeer %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// PatchWireGuardPeerStatus patches only the status of a WireGuardPeer resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchWireGuardPeerStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("WireGuardPeer UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadWireGuardPeer(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("WireGuardPeer not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Touch()

	if err := storage.SaveWireGuardPeer(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched WireGuardPeer status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourcePatched(r.Context(), "WireGuardPeer", res.GetUID(), res.GetName(), res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for WireGuardPeer %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteWireGuardPeer deletes a WireGuardPeer resource
func DeleteWireGuardPeer(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("WireGuardPeer UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	wireGuardPeer, err := storage.LoadWireGuardPeer(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("WireGuardPeer not found: %w", err))
		return
	}

	if err := storage.DeleteWireGuardPeer(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete WireGuardPeer: %w", err))
		return
	}

	if err := removeWireGuardPeer(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to remove WireGuardPeer: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}
	if err := events.PublishResourceDeleted(r.Context(), "WireGuardPeer", wireGuardPeer.GetUID(), wireGuardPeer.GetName(), deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for WireGuardPeer %s: %v\n", wireGuardPeer.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "WireGuardPeer deleted successfully",
		UID:     uid,
	})
}
