// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//   1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//   2. Run 'make dev' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource spec
//   - PatchResource(ctx, uid, patchData, contentType) - Patch existing resource spec
//   - UpdateResourceStatus(ctx, uid, status) - Update resource status only
//   - PatchResourceStatus(ctx, uid, patchData) - Patch resource status only
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//   client, err := client.NewClient("http://localhost:8080", nil)
//   if err != nil {
//       log.Fatal(err)
//   }
//
//   bmcs, err := client.GetBMCs(context.Background())
//   if err != nil {
//       log.Fatal(err)
//   }
//
// To add authentication:
//   1. Create custom http.Client with auth transport
//   2. Pass it to NewClient:
//      httpClient := &http.Client{
//          Transport: &AuthTransport{Token: "your-token"},
//      }
//      client, _ := client.NewClient(baseURL, httpClient)
//
// To add custom headers:
//   1. Modify doRequest method to accept header options
//   2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//   1. Wrap http.Client with retry transport
//   2. Use github.com/hashicorp/go-retryablehttp or similar
//

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"

	"github.com/OpenCHAMI/cloud-init/apis/cloud-init.openchami.io/v1"
)

// Client provides access to the inventory API
type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
	version    string // Optional API version for Accept/Content-Type headers
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:    c.baseURL,
		httpClient: c.httpClient,
		version:    version,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// doPatchRequest performs a PATCH request with custom content type
func (c *Client) doPatchRequest(ctx context.Context, endpoint string, patchData []byte, contentType string, result interface{}) error {
	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, "PATCH", u.String(), bytes.NewBuffer(patchData))
	if err != nil {
		return fmt.Errorf("failed to create patch request: %w", err)
	}

	// Set patch-specific Content-Type
	req.Header.Set("Content-Type", contentType)

	// Set Accept header with optional version
	acceptType := "application/json"
	if c.version != "" {
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("patch request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read patch response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("PATCH HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("PATCH API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal patch response: %w", err)
		}
	}

	return nil
}

// GetClusterDefaultss retrieves all clusterdefaultss
func (c *Client) GetClusterDefaultss(ctx context.Context) ([]v1.ClusterDefaults, error) {
	var response []v1.ClusterDefaults
	if err := c.doRequest(ctx, "GET", "/clusterdefaultss", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetClusterDefaults retrieves a specific ClusterDefaults by UID
func (c *Client) GetClusterDefaults(ctx context.Context, uid string) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateClusterDefaults creates a new ClusterDefaults
func (c *Client) CreateClusterDefaults(ctx context.Context, req CreateClusterDefaultsRequest) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	if err := c.doRequest(ctx, "POST", "/clusterdefaultss", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateClusterDefaults updates an existing ClusterDefaults
func (c *Client) UpdateClusterDefaults(ctx context.Context, uid string, req UpdateClusterDefaultsRequest) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchClusterDefaults patches an existing ClusterDefaults spec with the specified patch data and content type
func (c *Client) PatchClusterDefaults(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateClusterDefaultsStatus updates only the status of an existing ClusterDefaults
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateClusterDefaultsStatus(ctx context.Context, uid string, status v1.ClusterDefaultsStatus) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchClusterDefaultsStatus patches only the status of an existing ClusterDefaults
// Supports JSON Merge Patch by default. Use PatchClusterDefaultsStatusWithType for other patch formats.
func (c *Client) PatchClusterDefaultsStatus(ctx context.Context, uid string, patchData []byte) (*v1.ClusterDefaults, error) {
	return c.PatchClusterDefaultsStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchClusterDefaultsStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchClusterDefaultsStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteClusterDefaults deletes a ClusterDefaults by UID
func (c *Client) DeleteClusterDefaults(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetGroups retrieves all groups
func (c *Client) GetGroups(ctx context.Context) ([]v1.Group, error) {
	var response []v1.Group
	if err := c.doRequest(ctx, "GET", "/groups", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetGroup retrieves a specific Group by UID
func (c *Client) GetGroup(ctx context.Context, uid string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateGroup creates a new Group
func (c *Client) CreateGroup(ctx context.Context, req CreateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	if err := c.doRequest(ctx, "POST", "/groups", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroup updates an existing Group
func (c *Client) UpdateGroup(ctx context.Context, uid string, req UpdateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroup patches an existing Group spec with the specified patch data and content type
func (c *Client) PatchGroup(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroupStatus updates only the status of an existing Group
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateGroupStatus(ctx context.Context, uid string, status v1.GroupStatus) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroupStatus patches only the status of an existing Group
// Supports JSON Merge Patch by default. Use PatchGroupStatusWithType for other patch formats.
func (c *Client) PatchGroupStatus(ctx context.Context, uid string, patchData []byte) (*v1.Group, error) {
	return c.PatchGroupStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchGroupStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchGroupStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteGroup deletes a Group by UID
func (c *Client) DeleteGroup(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/groups/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetInstanceInfos retrieves all instanceinfos
func (c *Client) GetInstanceInfos(ctx context.Context) ([]v1.InstanceInfo, error) {
	var response []v1.InstanceInfo
	if err := c.doRequest(ctx, "GET", "/instanceinfos", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetInstanceInfo retrieves a specific InstanceInfo by UID
func (c *Client) GetInstanceInfo(ctx context.Context, uid string) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateInstanceInfo creates a new InstanceInfo
func (c *Client) CreateInstanceInfo(ctx context.Context, req CreateInstanceInfoRequest) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	if err := c.doRequest(ctx, "POST", "/instanceinfos", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateInstanceInfo updates an existing InstanceInfo
func (c *Client) UpdateInstanceInfo(ctx context.Context, uid string, req UpdateInstanceInfoRequest) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchInstanceInfo patches an existing InstanceInfo spec with the specified patch data and content type
func (c *Client) PatchInstanceInfo(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateInstanceInfoStatus updates only the status of an existing InstanceInfo
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateInstanceInfoStatus(ctx context.Context, uid string, status v1.InstanceInfoStatus) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchInstanceInfoStatus patches only the status of an existing InstanceInfo
// Supports JSON Merge Patch by default. Use PatchInstanceInfoStatusWithType for other patch formats.
func (c *Client) PatchInstanceInfoStatus(ctx context.Context, uid string, patchData []byte) (*v1.InstanceInfo, error) {
	return c.PatchInstanceInfoStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchInstanceInfoStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchInstanceInfoStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteInstanceInfo deletes a InstanceInfo by UID
func (c *Client) DeleteInstanceInfo(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetProfiles retrieves all profiles
func (c *Client) GetProfiles(ctx context.Context) ([]v1.Profile, error) {
	var response []v1.Profile
	if err := c.doRequest(ctx, "GET", "/profiles", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetProfile retrieves a specific Profile by UID
func (c *Client) GetProfile(ctx context.Context, uid string) (*v1.Profile, error) {
	var result v1.Profile
	endpoint := fmt.Sprintf("/profiles/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateProfile creates a new Profile
func (c *Client) CreateProfile(ctx context.Context, req CreateProfileRequest) (*v1.Profile, error) {
	var result v1.Profile
	if err := c.doRequest(ctx, "POST", "/profiles", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateProfile updates an existing Profile
func (c *Client) UpdateProfile(ctx context.Context, uid string, req UpdateProfileRequest) (*v1.Profile, error) {
	var result v1.Profile
	endpoint := fmt.Sprintf("/profiles/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchProfile patches an existing Profile spec with the specified patch data and content type
func (c *Client) PatchProfile(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Profile, error) {
	var result v1.Profile
	endpoint := fmt.Sprintf("/profiles/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateProfileStatus updates only the status of an existing Profile
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateProfileStatus(ctx context.Context, uid string, status v1.ProfileStatus) (*v1.Profile, error) {
	var result v1.Profile
	endpoint := fmt.Sprintf("/profiles/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchProfileStatus patches only the status of an existing Profile
// Supports JSON Merge Patch by default. Use PatchProfileStatusWithType for other patch formats.
func (c *Client) PatchProfileStatus(ctx context.Context, uid string, patchData []byte) (*v1.Profile, error) {
	return c.PatchProfileStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchProfileStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchProfileStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Profile, error) {
	var result v1.Profile
	endpoint := fmt.Sprintf("/profiles/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteProfile deletes a Profile by UID
func (c *Client) DeleteProfile(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/profiles/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetWireGuardPeers retrieves all wireguardpeers
func (c *Client) GetWireGuardPeers(ctx context.Context) ([]v1.WireGuardPeer, error) {
	var response []v1.WireGuardPeer
	if err := c.doRequest(ctx, "GET", "/wireguardpeers", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetWireGuardPeer retrieves a specific WireGuardPeer by UID
func (c *Client) GetWireGuardPeer(ctx context.Context, uid string) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateWireGuardPeer creates a new WireGuardPeer
func (c *Client) CreateWireGuardPeer(ctx context.Context, req CreateWireGuardPeerRequest) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	if err := c.doRequest(ctx, "POST", "/wireguardpeers", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWireGuardPeer updates an existing WireGuardPeer
func (c *Client) UpdateWireGuardPeer(ctx context.Context, uid string, req UpdateWireGuardPeerRequest) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchWireGuardPeer patches an existing WireGuardPeer spec with the specified patch data and content type
func (c *Client) PatchWireGuardPeer(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWireGuardPeerStatus updates only the status of an existing WireGuardPeer
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateWireGuardPeerStatus(ctx context.Context, uid string, status v1.WireGuardPeerStatus) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchWireGuardPeerStatus patches only the status of an existing WireGuardPeer
// Supports JSON Merge Patch by default. Use PatchWireGuardPeerStatusWithType for other patch formats.
func (c *Client) PatchWireGuardPeerStatus(ctx context.Context, uid string, patchData []byte) (*v1.WireGuardPeer, error) {
	return c.PatchWireGuardPeerStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchWireGuardPeerStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchWireGuardPeerStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteWireGuardPeer deletes a WireGuardPeer by UID
func (c *Client) DeleteWireGuardPeer(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
