// Code generated by Fabrica v0.4.9 (commit: 70cad05). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//   1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetHealth(ctx) - Get service health status
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource spec
//   - PatchResource(ctx, uid, patchData, contentType) - Patch existing resource spec
//   - UpdateResourceStatus(ctx, uid, status) - Update resource status only
//   - PatchResourceStatus(ctx, uid, patchData) - Patch resource status only
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//   client, err := client.NewClient("http://localhost:8080", nil, client.DefaultLogger())
//   if err != nil {
//       log.Fatal(err)
//   }
//
//   bmcs, err := client.GetBMCs(context.Background())
//   if err != nil {
//       log.Fatal(err)
//   }
//
// To add authentication:
//   1. Create custom http.Client with auth transport
//   2. Pass it to NewClient:
//      httpClient := &http.Client{
//          Transport: &AuthTransport{Token: "your-token"},
//      }
//      client, _ := client.NewClient(baseURL, httpClient, client.DefaultLogger)
//
// To add custom headers:
//   1. Modify doRequest method to accept header options
//   2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//   1. Wrap http.Client with retry transport
//   2. Use github.com/hashicorp/go-retryablehttp or similar
//

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path"

	"github.com/openchami/fabrica/pkg/fabrica"
	"github.com/rs/zerolog"
	"github.com/spf13/cobra"

	"github.com/openchami/metadata-service/apis/cloud-init.openchami.io/v1"
)

// Client provides access to the inventory API
type Client struct {
	baseURL     *url.URL
	httpClient  *http.Client
	logger      zerolog.Logger
	version     string // Optional API version for Accept/Content-Type headers
	bearerToken string // Optional JWT bearer token for Authorization header
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse represents a generic service health payload.
// Services may return additional fields beyond the common ones.
type HealthResponse map[string]interface{}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client, logger zerolog.Logger) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
		logger:     logger,
	}, nil
}

// NewClientWithBearerToken creates a new API client configured with a JWT bearer token.
func NewClientWithBearerToken(baseURL, bearerToken string, httpClient *http.Client, logger zerolog.Logger) (*Client, error) {
	c, err := NewClient(baseURL, httpClient, logger)
	if err != nil {
		return nil, err
	}
	return c.WithBearerToken(bearerToken), nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:     c.baseURL,
		httpClient:  c.httpClient,
		version:     version,
		bearerToken: c.bearerToken,
		logger:      c.logger,
	}
}

// WithBearerToken returns a new client configured to send Authorization: Bearer <token>.
func (c *Client) WithBearerToken(token string) *Client {
	return &Client{
		baseURL:     c.baseURL,
		httpClient:  c.httpClient,
		version:     c.version,
		bearerToken: token,
		logger:      c.logger,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)
	if c.bearerToken != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.bearerToken))
	}

	// Debug info for request
	c.logger.Debug().Msgf("%s: %s", method, u.String())
	if len(req.Header) > 0 {
		c.logger.Debug().Msg("Request headers:")
		for k, v := range req.Header {
			c.logger.Debug().Msgf("  %s: %s", k, v)
		}
	} else {
		c.logger.Debug().Msg("No headers in request")
	}
	if req.ContentLength > 0 {
		var reqBodyCopy bytes.Buffer
		reqBodyReader := io.TeeReader(req.Body, &reqBodyCopy)
		reqBodyBytes, err := io.ReadAll(reqBodyReader)
		if err != nil {
			c.logger.Error().Err(err).Msg("failed to read body for debug message")
		}
		c.logger.Debug().Msg("Request body:")
		c.logger.Debug().Msgf("%s", string(reqBodyBytes))
		req.Body = io.NopCloser(bytes.NewReader(reqBodyBytes))
	} else {
		c.logger.Debug().Msg("No body in request")
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	// Debug info for response
	if resp != nil {
		c.logger.Debug().Msg("Response status: " + resp.Status)
		if len(resp.Header) > 0 {
			c.logger.Debug().Msg("Response headers:")
			for k, v := range resp.Header {
				c.logger.Debug().Msgf("  %s: %s", k, v)
			}
		} else {
			c.logger.Debug().Msg("No headers in response")
		}
		respBodyLen := resp.ContentLength
		if respBodyLen > 0 {
			var respBodyCopy bytes.Buffer
			respBodyReader := io.TeeReader(resp.Body, &respBodyCopy)
			respBodyBytes, err := io.ReadAll(respBodyReader)
			if err != nil {
				c.logger.Error().Err(err).Msg("failed to read body for debug message")
			}
			c.logger.Debug().Msg("Response body:")
			c.logger.Debug().Msgf("%s", string(respBodyBytes))
			resp.Body = io.NopCloser(bytes.NewReader(respBodyBytes))
		} else {
			c.logger.Debug().Msg("No body in response")
		}
	} else {
		c.logger.Debug().Msg("Response was nil")
	}

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// doPatchRequest performs a PATCH request with custom content type
func (c *Client) doPatchRequest(ctx context.Context, endpoint string, patchData []byte, contentType string, result interface{}) error {
	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, "PATCH", u.String(), bytes.NewBuffer(patchData))
	if err != nil {
		return fmt.Errorf("failed to create patch request: %w", err)
	}

	// Set patch-specific Content-Type
	req.Header.Set("Content-Type", contentType)

	// Set Accept header with optional version
	acceptType := "application/json"
	if c.version != "" {
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}
	req.Header.Set("Accept", acceptType)
	if c.bearerToken != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.bearerToken))
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("patch request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read patch response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("PATCH HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("PATCH API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal patch response: %w", err)
		}
	}

	return nil
}

// GetHealth retrieves the service health endpoint response.
func (c *Client) GetHealth(ctx context.Context) (HealthResponse, error) {
	result := HealthResponse{}
	if err := c.doRequest(ctx, "GET", "health", nil, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// GetClusterDefaultss retrieves all clusterdefaultss
func (c *Client) GetClusterDefaultss(ctx context.Context) ([]v1.ClusterDefaults, error) {
	var response []v1.ClusterDefaults
	if err := c.doRequest(ctx, "GET", "/clusterdefaultss", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetClusterDefaults retrieves a specific ClusterDefaults by UID
func (c *Client) GetClusterDefaults(ctx context.Context, uid string) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateClusterDefaultsSimple creates a new ClusterDefaults with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateClusterDefaults instead.
//
// Example:
//
//	spec := v1.ClusterDefaultsSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateClusterDefaultsSimple(ctx, "my-resource", spec)
func (c *Client) CreateClusterDefaultsSimple(ctx context.Context, name string, spec v1.ClusterDefaultsSpec) (*v1.ClusterDefaults, error) {
	req := CreateClusterDefaultsRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateClusterDefaults(ctx, req)
}

// CreateClusterDefaults creates a new ClusterDefaults (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateClusterDefaultsSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateClusterDefaultsRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateClusterDefaults(ctx, req)
func (c *Client) CreateClusterDefaults(ctx context.Context, req CreateClusterDefaultsRequest) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	if err := c.doRequest(ctx, "POST", "/clusterdefaultss", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateClusterDefaultsSimple updates an existing ClusterDefaults's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateClusterDefaults instead.
//
// Example:
//
//	spec := v1.ClusterDefaultsSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateClusterDefaultsSimple(ctx, uid, spec)
func (c *Client) UpdateClusterDefaultsSimple(ctx context.Context, uid string, spec v1.ClusterDefaultsSpec) (*v1.ClusterDefaults, error) {
	req := UpdateClusterDefaultsRequest{
		Spec: spec,
	}
	return c.UpdateClusterDefaults(ctx, uid, req)
}

// UpdateClusterDefaults updates an existing ClusterDefaults (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateClusterDefaultsSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateClusterDefaultsRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateClusterDefaults(ctx, uid, req)
func (c *Client) UpdateClusterDefaults(ctx context.Context, uid string, req UpdateClusterDefaultsRequest) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchClusterDefaults patches an existing ClusterDefaults spec with the specified patch data and content type
func (c *Client) PatchClusterDefaults(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateClusterDefaultsStatus updates only the status of an existing ClusterDefaults
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateClusterDefaultsStatus(ctx context.Context, uid string, status v1.ClusterDefaultsStatus) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchClusterDefaultsStatus patches only the status of an existing ClusterDefaults
// Supports JSON Merge Patch by default. Use PatchClusterDefaultsStatusWithType for other patch formats.
func (c *Client) PatchClusterDefaultsStatus(ctx context.Context, uid string, patchData []byte) (*v1.ClusterDefaults, error) {
	return c.PatchClusterDefaultsStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchClusterDefaultsStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchClusterDefaultsStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ClusterDefaults, error) {
	var result v1.ClusterDefaults
	endpoint := fmt.Sprintf("/clusterdefaultss/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteClusterDefaults deletes a ClusterDefaults by UID
func (c *Client) DeleteClusterDefaults(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/clusterdefaultss/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetGroups retrieves all groups
func (c *Client) GetGroups(ctx context.Context) ([]v1.Group, error) {
	var response []v1.Group
	if err := c.doRequest(ctx, "GET", "/groups", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetGroup retrieves a specific Group by UID
func (c *Client) GetGroup(ctx context.Context, uid string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateGroupSimple creates a new Group with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateGroup instead.
//
// Example:
//
//	spec := v1.GroupSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateGroupSimple(ctx, "my-resource", spec)
func (c *Client) CreateGroupSimple(ctx context.Context, name string, spec v1.GroupSpec) (*v1.Group, error) {
	req := CreateGroupRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateGroup(ctx, req)
}

// CreateGroup creates a new Group (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateGroupSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateGroupRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateGroup(ctx, req)
func (c *Client) CreateGroup(ctx context.Context, req CreateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	if err := c.doRequest(ctx, "POST", "/groups", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroupSimple updates an existing Group's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateGroup instead.
//
// Example:
//
//	spec := v1.GroupSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateGroupSimple(ctx, uid, spec)
func (c *Client) UpdateGroupSimple(ctx context.Context, uid string, spec v1.GroupSpec) (*v1.Group, error) {
	req := UpdateGroupRequest{
		Spec: spec,
	}
	return c.UpdateGroup(ctx, uid, req)
}

// UpdateGroup updates an existing Group (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateGroupSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateGroupRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateGroup(ctx, uid, req)
func (c *Client) UpdateGroup(ctx context.Context, uid string, req UpdateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroup patches an existing Group spec with the specified patch data and content type
func (c *Client) PatchGroup(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroupStatus updates only the status of an existing Group
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateGroupStatus(ctx context.Context, uid string, status v1.GroupStatus) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroupStatus patches only the status of an existing Group
// Supports JSON Merge Patch by default. Use PatchGroupStatusWithType for other patch formats.
func (c *Client) PatchGroupStatus(ctx context.Context, uid string, patchData []byte) (*v1.Group, error) {
	return c.PatchGroupStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchGroupStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchGroupStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteGroup deletes a Group by UID
func (c *Client) DeleteGroup(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/groups/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetInstanceInfos retrieves all instanceinfos
func (c *Client) GetInstanceInfos(ctx context.Context) ([]v1.InstanceInfo, error) {
	var response []v1.InstanceInfo
	if err := c.doRequest(ctx, "GET", "/instanceinfos", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetInstanceInfo retrieves a specific InstanceInfo by UID
func (c *Client) GetInstanceInfo(ctx context.Context, uid string) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateInstanceInfoSimple creates a new InstanceInfo with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateInstanceInfo instead.
//
// Example:
//
//	spec := v1.InstanceInfoSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateInstanceInfoSimple(ctx, "my-resource", spec)
func (c *Client) CreateInstanceInfoSimple(ctx context.Context, name string, spec v1.InstanceInfoSpec) (*v1.InstanceInfo, error) {
	req := CreateInstanceInfoRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateInstanceInfo(ctx, req)
}

// CreateInstanceInfo creates a new InstanceInfo (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateInstanceInfoSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateInstanceInfoRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateInstanceInfo(ctx, req)
func (c *Client) CreateInstanceInfo(ctx context.Context, req CreateInstanceInfoRequest) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	if err := c.doRequest(ctx, "POST", "/instanceinfos", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateInstanceInfoSimple updates an existing InstanceInfo's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateInstanceInfo instead.
//
// Example:
//
//	spec := v1.InstanceInfoSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateInstanceInfoSimple(ctx, uid, spec)
func (c *Client) UpdateInstanceInfoSimple(ctx context.Context, uid string, spec v1.InstanceInfoSpec) (*v1.InstanceInfo, error) {
	req := UpdateInstanceInfoRequest{
		Spec: spec,
	}
	return c.UpdateInstanceInfo(ctx, uid, req)
}

// UpdateInstanceInfo updates an existing InstanceInfo (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateInstanceInfoSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateInstanceInfoRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateInstanceInfo(ctx, uid, req)
func (c *Client) UpdateInstanceInfo(ctx context.Context, uid string, req UpdateInstanceInfoRequest) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchInstanceInfo patches an existing InstanceInfo spec with the specified patch data and content type
func (c *Client) PatchInstanceInfo(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateInstanceInfoStatus updates only the status of an existing InstanceInfo
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateInstanceInfoStatus(ctx context.Context, uid string, status v1.InstanceInfoStatus) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchInstanceInfoStatus patches only the status of an existing InstanceInfo
// Supports JSON Merge Patch by default. Use PatchInstanceInfoStatusWithType for other patch formats.
func (c *Client) PatchInstanceInfoStatus(ctx context.Context, uid string, patchData []byte) (*v1.InstanceInfo, error) {
	return c.PatchInstanceInfoStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchInstanceInfoStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchInstanceInfoStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.InstanceInfo, error) {
	var result v1.InstanceInfo
	endpoint := fmt.Sprintf("/instanceinfos/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteInstanceInfo deletes a InstanceInfo by UID
func (c *Client) DeleteInstanceInfo(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/instanceinfos/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetWireGuardPeers retrieves all wireguardpeers
func (c *Client) GetWireGuardPeers(ctx context.Context) ([]v1.WireGuardPeer, error) {
	var response []v1.WireGuardPeer
	if err := c.doRequest(ctx, "GET", "/wireguardpeers", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetWireGuardPeer retrieves a specific WireGuardPeer by UID
func (c *Client) GetWireGuardPeer(ctx context.Context, uid string) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateWireGuardPeerSimple creates a new WireGuardPeer with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateWireGuardPeer instead.
//
// Example:
//
//	spec := v1.WireGuardPeerSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateWireGuardPeerSimple(ctx, "my-resource", spec)
func (c *Client) CreateWireGuardPeerSimple(ctx context.Context, name string, spec v1.WireGuardPeerSpec) (*v1.WireGuardPeer, error) {
	req := CreateWireGuardPeerRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateWireGuardPeer(ctx, req)
}

// CreateWireGuardPeer creates a new WireGuardPeer (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateWireGuardPeerSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateWireGuardPeerRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateWireGuardPeer(ctx, req)
func (c *Client) CreateWireGuardPeer(ctx context.Context, req CreateWireGuardPeerRequest) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	if err := c.doRequest(ctx, "POST", "/wireguardpeers", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWireGuardPeerSimple updates an existing WireGuardPeer's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateWireGuardPeer instead.
//
// Example:
//
//	spec := v1.WireGuardPeerSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateWireGuardPeerSimple(ctx, uid, spec)
func (c *Client) UpdateWireGuardPeerSimple(ctx context.Context, uid string, spec v1.WireGuardPeerSpec) (*v1.WireGuardPeer, error) {
	req := UpdateWireGuardPeerRequest{
		Spec: spec,
	}
	return c.UpdateWireGuardPeer(ctx, uid, req)
}

// UpdateWireGuardPeer updates an existing WireGuardPeer (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateWireGuardPeerSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateWireGuardPeerRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateWireGuardPeer(ctx, uid, req)
func (c *Client) UpdateWireGuardPeer(ctx context.Context, uid string, req UpdateWireGuardPeerRequest) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchWireGuardPeer patches an existing WireGuardPeer spec with the specified patch data and content type
func (c *Client) PatchWireGuardPeer(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWireGuardPeerStatus updates only the status of an existing WireGuardPeer
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateWireGuardPeerStatus(ctx context.Context, uid string, status v1.WireGuardPeerStatus) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchWireGuardPeerStatus patches only the status of an existing WireGuardPeer
// Supports JSON Merge Patch by default. Use PatchWireGuardPeerStatusWithType for other patch formats.
func (c *Client) PatchWireGuardPeerStatus(ctx context.Context, uid string, patchData []byte) (*v1.WireGuardPeer, error) {
	return c.PatchWireGuardPeerStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchWireGuardPeerStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchWireGuardPeerStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.WireGuardPeer, error) {
	var result v1.WireGuardPeer
	endpoint := fmt.Sprintf("/wireguardpeers/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteWireGuardPeer deletes a WireGuardPeer by UID
func (c *Client) DeleteWireGuardPeer(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/wireguardpeers/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// LogLevel represents a valid log level
type LogLevel string

const (
	LogLevelInfo    LogLevel = "info"
	LogLevelWarning LogLevel = "warning"
	LogLevelDebug   LogLevel = "debug"
)

var (
	LogLevelHelp = map[string]string{
		string(LogLevelInfo):    "Info log level",
		string(LogLevelWarning): "Warning log level",
		string(LogLevelDebug):   "Debug log level",
	}
)

func (ll LogLevel) String() string {
	return string(ll)
}

func (ll *LogLevel) Set(v string) error {
	switch LogLevel(v) {
	case LogLevelInfo,
		LogLevelWarning,
		LogLevelDebug:
		*ll = LogLevel(v)
		return nil
	default:
		return fmt.Errorf("must be one of %v", []LogLevel{
			LogLevelInfo,
			LogLevelWarning,
			LogLevelDebug,
		})
	}
}

func (ll LogLevel) Type() string {
	return "LogLevel"
}

// CompletionLogLevel is the cobra completion function for the --log-level
// flag.
func CompletionLogLevel(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
	var helpSlice []string
	for k, v := range LogLevelHelp {
		helpSlice = append(helpSlice, fmt.Sprintf("%s\t%s", k, v))
	}
	return helpSlice, cobra.ShellCompDirectiveDefault
}

func DefaultLogger() zerolog.Logger {
	cw := zerolog.ConsoleWriter{
		Out:          os.Stderr,
		PartsExclude: []string{zerolog.TimestampFieldName},
	}
	return zerolog.New(cw).Level(zerolog.WarnLevel)
}

func NewLogger(level LogLevel) (zerolog.Logger, error) {
	cw := zerolog.ConsoleWriter{
		Out:          os.Stderr,
		PartsExclude: []string{zerolog.TimestampFieldName},
	}
	l := zerolog.New(cw)
	var ll zerolog.Level
	switch level {
	case LogLevelWarning:
		ll = zerolog.WarnLevel
	case LogLevelInfo:
		ll = zerolog.InfoLevel
	case LogLevelDebug:
		ll = zerolog.DebugLevel
	default:
		return DefaultLogger(), fmt.Errorf("invalid log level: %s", level)
	}
	return l.Level(ll), nil
}
