// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2025 OpenCHAMI Contributors

/*
Package client provides the auto-generated REST API client for the cloud-init metadata service.

This package contains the client-side implementation for interacting with the metadata service
REST API. It is automatically generated by the Fabrica framework and should NOT be manually edited.

The generated client provides type-safe access to all resource management operations without
requiring manual HTTP request construction.

# Client Structure

The package includes:
  - REST client implementation with HTTP transport
  - Request/response models matching server implementations
  - Resource-specific client methods
  - Error handling and response validation

# Generated Resource Clients

Each resource type (Group, ClusterDefaults, InstanceInfo) has generated client methods:

	Groups:
	  - CreateGroup(ctx, groupRequest) (*Group, error)
	  - ListGroups(ctx) ([]*Group, error)
	  - GetGroup(ctx, id) (*Group, error)
	  - UpdateGroup(ctx, id, patchRequest) (*Group, error)
	  - DeleteGroup(ctx, id) error

	ClusterDefaults:
	  - CreateClusterDefaults(ctx, request) (*ClusterDefaults, error)
	  - ListClusterDefaults(ctx) ([]*ClusterDefaults, error)
	  - GetClusterDefaults(ctx, id) (*ClusterDefaults, error)
	  - UpdateClusterDefaults(ctx, id, patchRequest) (*ClusterDefaults, error)
	  - DeleteClusterDefaults(ctx, id) error

	InstanceInfo:
	  - CreateInstanceInfo(ctx, request) (*InstanceInfo, error)
	  - ListInstanceInfo(ctx) ([]*InstanceInfo, error)
	  - GetInstanceInfo(ctx, id) (*InstanceInfo, error)
	  - UpdateInstanceInfo(ctx, id, patchRequest) (*InstanceInfo, error)
	  - DeleteInstanceInfo(ctx, id) error

Usage Example

	package main

	import (
	    "context"
	    "log"
	    "github.com/OpenCHAMI/cloud-init/pkg/client"
	)

	func main() {
	    // Create client connected to server
	    c := client.NewClient("http://localhost:8080")

	    ctx := context.Background()

	    // Create a group
	    group := &client.Group{
	        Name: "compute",
	        Spec: client.GroupSpec{
	            Template: "#cloud-config\npackages:\n  - gcc",
	            MetaData: map[string]string{
	                "role": "compute",
	            },
	        },
	    }

	    created, err := c.CreateGroup(ctx, group)
	    if err != nil {
	        log.Fatal(err)
	    }
	    log.Printf("Created group with ID: %s", created.UID)

	    // List all groups
	    groups, err := c.ListGroups(ctx)
	    if err != nil {
	        log.Fatal(err)
	    }
	    log.Printf("Found %d groups", len(groups))

	    // Get specific group
	    retrieved, err := c.GetGroup(ctx, created.UID)
	    if err != nil {
	        log.Fatal(err)
	    }
	    log.Printf("Retrieved group: %s", retrieved.Name)

	    // Update group
	    update := map[string]interface{}{
	        "spec": map[string]interface{}{
	            "template": "#cloud-config\npackages:\n  - gcc\n  - mpi",
	        },
	    }
	    updated, err := c.UpdateGroup(ctx, created.UID, update)
	    if err != nil {
	        log.Fatal(err)
	    }
	    log.Printf("Updated group version: %s", updated.Status.LastTemplateVersion)

	    // Delete group
	    err = c.DeleteGroup(ctx, created.UID)
	    if err != nil {
	        log.Fatal(err)
	    }
	    log.Println("Deleted group")
	}

# Client Initialization

Create a client with default settings:

	client := client.NewClient("http://localhost:8080")

Create a client with custom configuration:

	client := client.NewClientWithConfig(
	    "http://localhost:8080",
	    &client.ClientConfig{
	        Timeout: 30 * time.Second,
	        Headers: map[string]string{
	            "Authorization": "Bearer token",
	        },
	    },
	)

# Request Patterns

All resource operations follow these patterns:

Create Operations:

	resource := &client.ResourceType{
	    Name: "example",
	    Spec: client.ResourceSpec{...},
	}
	created, err := c.CreateResourceType(ctx, resource)

List Operations:

	resources, err := c.ListResourceType(ctx)
	for _, r := range resources {
	    log.Printf("Found: %s", r.Name)
	}

Get Operations:

	resource, err := c.GetResourceType(ctx, id)

Update Operations (PATCH - partial updates only):

	update := map[string]interface{}{
	    "spec": map[string]interface{}{
	        "field": "new_value",
	    },
	}
	updated, err := c.UpdateResourceType(ctx, id, update)

Delete Operations:

	err := c.DeleteResourceType(ctx, id)

# Resource Identification

Resources are identified by their UID (unique ID) generated by the server:
  - All list operations return resources with their UID
  - All get/update/delete operations require the UID, not the name
  - Resource names are logical identifiers, UIDs are primary keys

# Context Usage

All client methods accept a context.Context parameter:
  - Use context for timeouts: ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
  - Use context for cancellation: ctx, cancel := context.WithCancel(context.Background())
  - Use context for request-scoped values: context.WithValue()

# Error Handling

Client methods return errors in these categories:

  - HTTP errors: Non-2xx responses from server
  - Validation errors: Request validation failures
  - Network errors: Connection or timeout issues
  - Parsing errors: Response JSON parsing failures

Check error types to implement appropriate retry or fallback logic:

	created, err := c.CreateGroup(ctx, group)
	if err != nil {
	    if client.IsNotFound(err) {
	        // Resource not found
	    } else if client.IsConflict(err) {
	        // Resource already exists
	    } else if client.IsValidationError(err) {
	        // Invalid request
	    } else {
	        // Other errors
	    }
	}

# Command-Line Client

For convenient CLI access, use the generated CLI client:

	go run ./cmd/client/main.go --server http://localhost:8080 \
	    group create --spec '{"name":"compute","template":"#cloud-config"}'

	go run ./cmd/client/main.go --server http://localhost:8080 group list

	go run ./cmd/client/main.go --server http://localhost:8080 \
	    group get <id>

	go run ./cmd/client/main.go --server http://localhost:8080 \
	    group update <id> --spec '{"spec":{"template":"..."}}'

	go run ./cmd/client/main.go --server http://localhost:8080 group delete <id>

# Integration Testing

Use the client in integration tests:

	func TestGroupWorkflow(t *testing.T) {
	    client := client.NewClient("http://localhost:8080")
	    ctx := context.Background()

	    // Create
	    group := &client.Group{Name: "test", Spec: client.GroupSpec{...}}
	    created, err := client.CreateGroup(ctx, group)
	    require.NoError(t, err)

	    // Retrieve
	    retrieved, err := client.GetGroup(ctx, created.UID)
	    require.NoError(t, err)
	    assert.Equal(t, created.UID, retrieved.UID)

	    // Cleanup
	    require.NoError(t, client.DeleteGroup(ctx, created.UID))
	}

# Regeneration

This package is auto-generated by Fabrica. To regenerate after server changes:

	fabrica generate

All client code will be updated to match the current server implementation.
Manual edits to this package will be lost during regeneration.
*/
package client
