// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains client-side request/response models.
// Generated from: pkg/codegen/templates/client-models.go.tmpl
//
// To modify client models:
//   1. Edit the template file: pkg/codegen/templates/client-models.go.tmpl
//   2. Run 'make dev' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// DEPRECATED: This template is a legacy stub. The actual client models are
// generated in models.go.tmpl and used by both server and client.
//
// Generated request types:
//   - CreateResourceRequest: Create operation with metadata
//   - UpdateResourceRequest: Update operation with partial fields
//   - DeleteResponse: Confirmation of deletion
//
// Note: This file contains TODO comments indicating that resource-specific
// fields should be added. Consider migrating to the unified models.go.tmpl
// approach or implementing spec field embedding.
//
// To implement full spec support:
//   1. Import resource packages
//   2. Embed ResourceSpec in request structs
//   3. Use json:",inline" tag for proper serialization
//
// To add validation:
//   1. Add validate tags (e.g., validate:"required,min=3")
//   2. Use go-playground/validator in client before sending
//

// Package client provides generated client-side request and response models.
package client

import (
	"github.com/openchami/fabrica/pkg/fabrica"

	"github.com/OpenCHAMI/cloud-init/apis/cloud-init.openchami.io/v1"
)

// CreateClusterDefaultsRequest represents a request to create a ClusterDefaults
type CreateClusterDefaultsRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata" validate:"required"`
	Spec        v1.ClusterDefaultsSpec `json:"spec" validate:"required"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// UpdateClusterDefaultsRequest represents a request to update a ClusterDefaults
type UpdateClusterDefaultsRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata,omitempty"`
	Spec        v1.ClusterDefaultsSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// CreateGroupRequest represents a request to create a Group
type CreateGroupRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.GroupSpec      `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// UpdateGroupRequest represents a request to update a Group
type UpdateGroupRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.GroupSpec      `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// CreateInstanceInfoRequest represents a request to create a InstanceInfo
type CreateInstanceInfoRequest struct {
	Metadata    fabrica.Metadata    `json:"metadata" validate:"required"`
	Spec        v1.InstanceInfoSpec `json:"spec" validate:"required"`
	Labels      map[string]string   `json:"labels,omitempty"`
	Annotations map[string]string   `json:"annotations,omitempty"`
}

// UpdateInstanceInfoRequest represents a request to update a InstanceInfo
type UpdateInstanceInfoRequest struct {
	Metadata    fabrica.Metadata    `json:"metadata,omitempty"`
	Spec        v1.InstanceInfoSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string   `json:"labels,omitempty"`
	Annotations map[string]string   `json:"annotations,omitempty"`
}

// CreateProfileRequest represents a request to create a Profile
type CreateProfileRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.ProfileSpec    `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// UpdateProfileRequest represents a request to update a Profile
type UpdateProfileRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.ProfileSpec    `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// CreateWireGuardPeerRequest represents a request to create a WireGuardPeer
type CreateWireGuardPeerRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata" validate:"required"`
	Spec        v1.WireGuardPeerSpec `json:"spec" validate:"required"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// UpdateWireGuardPeerRequest represents a request to update a WireGuardPeer
type UpdateWireGuardPeerRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata,omitempty"`
	Spec        v1.WireGuardPeerSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}
