// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Cobra-based CLI for the metadata_service API.
// Generated from: pkg/codegen/templates/client-cmd.go.tmpl
//
// To modify the CLI:
//  1. Edit the template file: pkg/codegen/templates/client-cmd.go.tmpl
//  2. Run 'make generate-client-cmd' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated commands for each resource:
//   - client health
//   - client clusterdefaults [list|get|create|update|patch|delete]
//   - client group [list|get|create|update|patch|delete]
//   - client instanceinfo [list|get|create|update|patch|delete]
//   - client wireguardpeer [list|get|create|update|patch|delete]
//
// Global flags (available for all commands):
//
//	--server       Server URL (env: METADATA_SERVICE_SERVER)
//	--timeout      Request timeout (env: METADATA_SERVICE_TIMEOUT)
//	--output, -o   Output format: table, json, yaml (env: METADATA_SERVICE_OUTPUT)
//	--version, -v  API version to request: v1, v2beta1, etc. (env: METADATA_SERVICE_VERSION)
//	--token        JWT bearer token (env: METADATA_SERVICE_TOKEN)
//	--show-token   Show the full bearer token in debug logs
//	--config       Config file path (default: ~/.metadata_service-cli.yaml)
//
// Configuration sources (in order of precedence):
//  1. Command-line flags
//  2. Environment variables (METADATA_SERVICE_*)
//  3. Config file (~/.metadata_service-cli.yaml)
//  4. Default values
//
// Usage examples:
//
//	# List all clusterdefaultss (default version)
//	client clusterdefaults list
//
//	# List clusterdefaultss with specific version
//	client clusterdefaults list --version v2beta1
//
//	# Get ClusterDefaults as v1
//	client clusterdefaults get <uid> --version v1
//
//	# Create from JSON file with version
//	cat clusterdefaults.json | client clusterdefaults create --version v2beta1
//
//	# Create from inline JSON
//	client clusterdefaults create --spec '{"name":"clusterdefaults-01","description":"Example ClusterDefaults"}'
//
//	# Use environment variables
//	export METADATA_SERVICE_SERVER=https://metadata_service.example.com
//	export METADATA_SERVICE_VERSION=v2beta1
//	client clusterdefaults list
//
// To add custom commands:
//  1. Add command definition in template after resource commands
//  2. Register it in init() function
//
// To change output formatting:
//  1. Modify printOutput function to add new formats
//  2. Update output flag validation
//
// To add authentication:
//  1. Add auth flags (--token, --username, etc.)
//  2. Modify getClient to configure auth in http.Client
//  3. Add auth headers in client package
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/openchami/metadata-service/pkg/client"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	cfgFile     string
	serverURL   string
	timeout     time.Duration
	output      string
	apiVersion  string
	bearerToken string
	showToken   bool
	logLevel    client.LogLevel
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   filepath.Base(os.Args[0]),
	Short: "metadata_service CLI",
	Long:  `A command-line interface for managing metadata_service resources.`,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.metadata_service-cli.yaml)")
	rootCmd.PersistentFlags().StringVar(&serverURL, "server", "http://localhost:8080", "metadata_service server URL")
	rootCmd.PersistentFlags().DurationVar(&timeout, "timeout", 30*time.Second, "request timeout")
	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "table", "output format: table, json, yaml")
	rootCmd.PersistentFlags().StringVarP(&apiVersion, "version", "v", "", "API version to request (e.g., v1, v2beta1)")
	rootCmd.PersistentFlags().StringVar(&bearerToken, "token", "", "JWT bearer token")
	rootCmd.PersistentFlags().BoolVar(&showToken, "show-token", false, "show full bearer token in debug logs instead of a truncated value")
	rootCmd.PersistentFlags().VarP(&logLevel, "log-level", "l", "set verbosity of logs (e.g., info, warning, debug)")

	// Register shell completion functions
	rootCmd.RegisterFlagCompletionFunc("log-level", client.CompletionLogLevel)

	// Bind flags to viper
	viper.BindPFlag("server", rootCmd.PersistentFlags().Lookup("server"))
	viper.BindPFlag("timeout", rootCmd.PersistentFlags().Lookup("timeout"))
	viper.BindPFlag("output", rootCmd.PersistentFlags().Lookup("output"))
	viper.BindPFlag("version", rootCmd.PersistentFlags().Lookup("version"))
	viper.BindPFlag("token", rootCmd.PersistentFlags().Lookup("token"))
	viper.BindPFlag("show-token", rootCmd.PersistentFlags().Lookup("show-token"))
	viper.BindPFlag("log-level", rootCmd.PersistentFlags().Lookup("log-level"))

	// Environment variable support
	viper.SetEnvPrefix("METADATA_SERVICE")
	viper.AutomaticEnv()

	// Add resource commands
	rootCmd.AddCommand(healthCmd)
	rootCmd.AddCommand(NewVersionCommand())
	rootCmd.AddCommand(clusterdefaultsCmd)
	rootCmd.AddCommand(groupCmd)
	rootCmd.AddCommand(instanceinfoCmd)
	rootCmd.AddCommand(wireguardpeerCmd)

}

func initConfig() {
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			return
		}

		viper.AddConfigPath(home)
		viper.SetConfigType("yaml")
		viper.SetConfigName(".metadata_service-cli")
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}

func getClient() (*client.Client, error) {
	serverURL := viper.GetString("server")
	// Error will cause default logger, which is handled by NewClient()
	logger, _ := client.NewLogger(logLevel)
	c, err := client.NewClient(serverURL, nil, logger)
	if err != nil {
		return nil, err
	}
	c = c.WithShowToken(viper.GetBool("show-token"))

	// Apply version if specified
	version := viper.GetString("version")
	if version != "" {
		c = c.WithVersion(version)
	}

	token := viper.GetString("token")
	if token != "" {
		c = c.WithBearerToken(token)
	}

	return c, nil
}

func printOutput(data interface{}) error {
	switch output {
	case "json":
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	case "yaml":
		// TODO: Add YAML support if needed
		return fmt.Errorf("YAML output not yet implemented")
	case "table":
		// Simple table output
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	default:
		return fmt.Errorf("unknown output format: %s", output)
	}
}

var healthCmd = &cobra.Command{
	Use:   "health",
	Short: "Get service health status",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		health, err := c.GetHealth(ctx)
		if err != nil {
			return fmt.Errorf("failed to get health status: %w", err)
		}

		return printOutput(health)
	},
}

// setNestedField sets a field in a nested map using dot notation
// Example: setNestedField(map, "status.health", "OK") sets map["status"]["health"] = "OK"
func setNestedField(target map[string]interface{}, path string, value interface{}) {
	parts := strings.Split(path, ".")
	current := target

	// Navigate to the parent of the target field
	for _, part := range parts[:len(parts)-1] {
		if current[part] == nil {
			current[part] = make(map[string]interface{})
		}
		if nested, ok := current[part].(map[string]interface{}); ok {
			current = nested
		} else {
			// Convert to map if it's not already
			current[part] = make(map[string]interface{})
			current = current[part].(map[string]interface{})
		}
	}

	// Set the final field
	finalField := parts[len(parts)-1]
	if value == nil {
		// For unset operations, we use JSON Merge Patch null semantics
		current[finalField] = nil
	} else if stringValue, ok := value.(string); ok {
		// Try to parse as JSON first, then as string
		var jsonValue interface{}
		if err := json.Unmarshal([]byte(stringValue), &jsonValue); err == nil {
			current[finalField] = jsonValue
		} else {
			current[finalField] = stringValue
		}
	} else {
		current[finalField] = value
	}
}

// ClusterDefaults commands
var clusterdefaultsCmd = &cobra.Command{
	Use:   "clusterdefaults",
	Short: "Manage clusterdefaultss",
	Long:  `Create, read, update, patch, and delete clusterdefaultss.`,
}

var clusterdefaultsListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all clusterdefaultss",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetClusterDefaultss(ctx)
		if err != nil {
			return fmt.Errorf("failed to list clusterdefaultss: %w", err)
		}

		return printOutput(items)
	},
}

var clusterdefaultsGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a ClusterDefaults by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetClusterDefaults(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get ClusterDefaults: %w", err)
		}

		return printOutput(item)
	},
}

var clusterdefaultsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new ClusterDefaults",
	Long: `Create a new ClusterDefaults.

Examples:
  # Create from stdin
  echo '{"description": "Example description", "base_url": "https://example.com", "cloud_provider": "example-value", "region": "example-value", "availability_zone": "example-value", "cluster_name": "example-name", "short_name": "example-name", "nid_length": 42, "public_keys": ["["item1","item2"]"]}' | client clusterdefaults create

  # Create with --spec flag
  client clusterdefaults create --spec '{"description": "Example description", "base_url": "https://example.com", "cloud_provider": "example-value", "region": "example-value", "availability_zone": "example-value", "cluster_name": "example-name", "short_name": "example-name", "nid_length": 42, "public_keys": ["["item1","item2"]"]}'

Spec fields:
  description (string)
  base_url (string) [required]
  cloud_provider (string)
  region (string)
  availability_zone (string)
  cluster_name (string) [required]
  short_name (string)
  nid_length (int)
  public_keys ([]string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateClusterDefaultsRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateClusterDefaults(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create ClusterDefaults: %w", err)
		}

		return printOutput(item)
	},
}

var clusterdefaultsUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing ClusterDefaults",
	Long: `Update an existing ClusterDefaults.

Examples:
  # Update from stdin
  echo '{"description": "Example description", "base_url": "https://example.com", "cloud_provider": "example-value", "region": "example-value", "availability_zone": "example-value", "cluster_name": "example-name", "short_name": "example-name", "nid_length": 42, "public_keys": ["["item1","item2"]"]}' | client clusterdefaults update <uid>

  # Update with --spec flag
  client clusterdefaults update <uid> --spec '{"description": "Example description", "base_url": "https://example.com", "cloud_provider": "example-value", "region": "example-value", "availability_zone": "example-value", "cluster_name": "example-name", "short_name": "example-name", "nid_length": 42, "public_keys": ["["item1","item2"]"]}'

Spec fields:
  description (string)
  base_url (string) [required]
  cloud_provider (string)
  region (string)
  availability_zone (string)
  cluster_name (string) [required]
  short_name (string)
  nid_length (int)
  public_keys ([]string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateClusterDefaultsRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateClusterDefaults(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update ClusterDefaults: %w", err)
		}

		return printOutput(item)
	},
}

var clusterdefaultsPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a ClusterDefaults",
	Long: `Patch an existing ClusterDefaults spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client clusterdefaults patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client clusterdefaults patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client clusterdefaults patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client clusterdefaults patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchClusterDefaults(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch ClusterDefaults: %w", err)
		}

		return printOutput(item)
	},
}

var clusterdefaultsDeleteCmd = &cobra.Command{
	Use:   "delete [uid...]",
	Short: "Delete one or more ClusterDefaults resources",
	Long: `Deletes one or more ClusterDefaults resources.

You can provide multiple UIDs separated by spaces to delete them all in a single command.
Each UID is processed one by one as an individual, atomic delete operation. If any deletion fails, the command will still attempt to delete the remaining UIDs and report the errors at the end.`,
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		var errs []error
		for _, uid := range args {
			if err := c.DeleteClusterDefaults(ctx, uid); err != nil {
				errs = append(errs, fmt.Errorf("failed to delete ClusterDefaults %q: %w", uid, err))
				continue
			}
			fmt.Printf("ClusterDefaults %s deleted successfully\n", uid)
		}

		if len(errs) > 0 {
			var errMsgs []string
			for _, e := range errs {
				errMsgs = append(errMsgs, e.Error())
			}
			return fmt.Errorf("encountered %d error(s) during deletion:\n%s", len(errs), strings.Join(errMsgs, "\n"))
		}
		return nil
	},
}

func init() {
	clusterdefaultsCmd.AddCommand(clusterdefaultsListCmd)
	clusterdefaultsCmd.AddCommand(clusterdefaultsGetCmd)
	clusterdefaultsCmd.AddCommand(clusterdefaultsCreateCmd)
	clusterdefaultsCmd.AddCommand(clusterdefaultsUpdateCmd)
	clusterdefaultsCmd.AddCommand(clusterdefaultsPatchCmd)
	clusterdefaultsCmd.AddCommand(clusterdefaultsDeleteCmd)

	// Add spec flag for create and update commands
	clusterdefaultsCreateCmd.Flags().String("spec", "", "ClusterDefaults specification in JSON format")
	clusterdefaultsUpdateCmd.Flags().String("spec", "", "ClusterDefaults specification in JSON format")

	// Add patch command flags
	clusterdefaultsPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	clusterdefaultsPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	clusterdefaultsPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	clusterdefaultsPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	clusterdefaultsPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	clusterdefaultsPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// Group commands
var groupCmd = &cobra.Command{
	Use:   "group",
	Short: "Manage groups",
	Long:  `Create, read, update, patch, and delete groups.`,
}

var groupListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all groups",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetGroups(ctx)
		if err != nil {
			return fmt.Errorf("failed to list groups: %w", err)
		}

		return printOutput(items)
	},
}

var groupGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a Group by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetGroup(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get Group: %w", err)
		}

		return printOutput(item)
	},
}

var groupCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new Group",
	Long: `Create a new Group.

Examples:
  # Create from stdin
  echo '{"description": "Example description", "template": "example-value", "metaData": {"{"key":"value"}": "value"}, "osVersion": "example-value"}' | client group create

  # Create with --spec flag
  client group create --spec '{"description": "Example description", "template": "example-value", "metaData": {"{"key":"value"}": "value"}, "osVersion": "example-value"}'

Spec fields:
  description (string)
  template (string)
  metaData (map[string]string)
  osVersion (string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateGroupRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateGroup(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create Group: %w", err)
		}

		return printOutput(item)
	},
}

var groupUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing Group",
	Long: `Update an existing Group.

Examples:
  # Update from stdin
  echo '{"description": "Example description", "template": "example-value", "metaData": {"{"key":"value"}": "value"}, "osVersion": "example-value"}' | client group update <uid>

  # Update with --spec flag
  client group update <uid> --spec '{"description": "Example description", "template": "example-value", "metaData": {"{"key":"value"}": "value"}, "osVersion": "example-value"}'

Spec fields:
  description (string)
  template (string)
  metaData (map[string]string)
  osVersion (string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateGroupRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateGroup(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update Group: %w", err)
		}

		return printOutput(item)
	},
}

var groupPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a Group",
	Long: `Patch an existing Group spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client group patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client group patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client group patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client group patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchGroup(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch Group: %w", err)
		}

		return printOutput(item)
	},
}

var groupDeleteCmd = &cobra.Command{
	Use:   "delete [uid...]",
	Short: "Delete one or more Group resources",
	Long: `Deletes one or more Group resources.

You can provide multiple UIDs separated by spaces to delete them all in a single command.
Each UID is processed one by one as an individual, atomic delete operation. If any deletion fails, the command will still attempt to delete the remaining UIDs and report the errors at the end.`,
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		var errs []error
		for _, uid := range args {
			if err := c.DeleteGroup(ctx, uid); err != nil {
				errs = append(errs, fmt.Errorf("failed to delete Group %q: %w", uid, err))
				continue
			}
			fmt.Printf("Group %s deleted successfully\n", uid)
		}

		if len(errs) > 0 {
			var errMsgs []string
			for _, e := range errs {
				errMsgs = append(errMsgs, e.Error())
			}
			return fmt.Errorf("encountered %d error(s) during deletion:\n%s", len(errs), strings.Join(errMsgs, "\n"))
		}
		return nil
	},
}

func init() {
	groupCmd.AddCommand(groupListCmd)
	groupCmd.AddCommand(groupGetCmd)
	groupCmd.AddCommand(groupCreateCmd)
	groupCmd.AddCommand(groupUpdateCmd)
	groupCmd.AddCommand(groupPatchCmd)
	groupCmd.AddCommand(groupDeleteCmd)

	// Add spec flag for create and update commands
	groupCreateCmd.Flags().String("spec", "", "Group specification in JSON format")
	groupUpdateCmd.Flags().String("spec", "", "Group specification in JSON format")

	// Add patch command flags
	groupPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	groupPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	groupPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	groupPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	groupPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	groupPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// InstanceInfo commands
var instanceinfoCmd = &cobra.Command{
	Use:   "instanceinfo",
	Short: "Manage instanceinfos",
	Long:  `Create, read, update, patch, and delete instanceinfos.`,
}

var instanceinfoListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all instanceinfos",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetInstanceInfos(ctx)
		if err != nil {
			return fmt.Errorf("failed to list instanceinfos: %w", err)
		}

		return printOutput(items)
	},
}

var instanceinfoGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a InstanceInfo by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetInstanceInfo(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get InstanceInfo: %w", err)
		}

		return printOutput(item)
	},
}

var instanceinfoCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new InstanceInfo",
	Long: `Create a new InstanceInfo.

Examples:
  # Create from stdin
  echo '{"description": "Example description", "instance_id": "example-value", "local_hostname": "example-name", "hostname": "example-name", "cloud_init_base_url": "https://example.com", "public_keys": ["["item1","item2"]"], "default_profile": "example-value"}' | client instanceinfo create

  # Create with --spec flag
  client instanceinfo create --spec '{"description": "Example description", "instance_id": "example-value", "local_hostname": "example-name", "hostname": "example-name", "cloud_init_base_url": "https://example.com", "public_keys": ["["item1","item2"]"], "default_profile": "example-value"}'

Spec fields:
  description (string)
  instance_id (string) [required]
  local_hostname (string)
  hostname (string)
  cloud_init_base_url (string)
  public_keys ([]string)
  default_profile (string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateInstanceInfoRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateInstanceInfo(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create InstanceInfo: %w", err)
		}

		return printOutput(item)
	},
}

var instanceinfoUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing InstanceInfo",
	Long: `Update an existing InstanceInfo.

Examples:
  # Update from stdin
  echo '{"description": "Example description", "instance_id": "example-value", "local_hostname": "example-name", "hostname": "example-name", "cloud_init_base_url": "https://example.com", "public_keys": ["["item1","item2"]"], "default_profile": "example-value"}' | client instanceinfo update <uid>

  # Update with --spec flag
  client instanceinfo update <uid> --spec '{"description": "Example description", "instance_id": "example-value", "local_hostname": "example-name", "hostname": "example-name", "cloud_init_base_url": "https://example.com", "public_keys": ["["item1","item2"]"], "default_profile": "example-value"}'

Spec fields:
  description (string)
  instance_id (string) [required]
  local_hostname (string)
  hostname (string)
  cloud_init_base_url (string)
  public_keys ([]string)
  default_profile (string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateInstanceInfoRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateInstanceInfo(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update InstanceInfo: %w", err)
		}

		return printOutput(item)
	},
}

var instanceinfoPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a InstanceInfo",
	Long: `Patch an existing InstanceInfo spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client instanceinfo patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client instanceinfo patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client instanceinfo patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client instanceinfo patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchInstanceInfo(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch InstanceInfo: %w", err)
		}

		return printOutput(item)
	},
}

var instanceinfoDeleteCmd = &cobra.Command{
	Use:   "delete [uid...]",
	Short: "Delete one or more InstanceInfo resources",
	Long: `Deletes one or more InstanceInfo resources.

You can provide multiple UIDs separated by spaces to delete them all in a single command.
Each UID is processed one by one as an individual, atomic delete operation. If any deletion fails, the command will still attempt to delete the remaining UIDs and report the errors at the end.`,
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		var errs []error
		for _, uid := range args {
			if err := c.DeleteInstanceInfo(ctx, uid); err != nil {
				errs = append(errs, fmt.Errorf("failed to delete InstanceInfo %q: %w", uid, err))
				continue
			}
			fmt.Printf("InstanceInfo %s deleted successfully\n", uid)
		}

		if len(errs) > 0 {
			var errMsgs []string
			for _, e := range errs {
				errMsgs = append(errMsgs, e.Error())
			}
			return fmt.Errorf("encountered %d error(s) during deletion:\n%s", len(errs), strings.Join(errMsgs, "\n"))
		}
		return nil
	},
}

func init() {
	instanceinfoCmd.AddCommand(instanceinfoListCmd)
	instanceinfoCmd.AddCommand(instanceinfoGetCmd)
	instanceinfoCmd.AddCommand(instanceinfoCreateCmd)
	instanceinfoCmd.AddCommand(instanceinfoUpdateCmd)
	instanceinfoCmd.AddCommand(instanceinfoPatchCmd)
	instanceinfoCmd.AddCommand(instanceinfoDeleteCmd)

	// Add spec flag for create and update commands
	instanceinfoCreateCmd.Flags().String("spec", "", "InstanceInfo specification in JSON format")
	instanceinfoUpdateCmd.Flags().String("spec", "", "InstanceInfo specification in JSON format")

	// Add patch command flags
	instanceinfoPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	instanceinfoPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	instanceinfoPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	instanceinfoPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	instanceinfoPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	instanceinfoPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// WireGuardPeer commands
var wireguardpeerCmd = &cobra.Command{
	Use:   "wireguardpeer",
	Short: "Manage wireguardpeers",
	Long:  `Create, read, update, patch, and delete wireguardpeers.`,
}

var wireguardpeerListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all wireguardpeers",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetWireGuardPeers(ctx)
		if err != nil {
			return fmt.Errorf("failed to list wireguardpeers: %w", err)
		}

		return printOutput(items)
	},
}

var wireguardpeerGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a WireGuardPeer by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetWireGuardPeer(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get WireGuardPeer: %w", err)
		}

		return printOutput(item)
	},
}

var wireguardpeerCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new WireGuardPeer",
	Long: `Create a new WireGuardPeer.

Examples:
  # Create from stdin
  echo '{"description": "Example description", "public_key": "example-value", "allowed_ip": "192.168.1.1"}' | client wireguardpeer create

  # Create with --spec flag
  client wireguardpeer create --spec '{"description": "Example description", "public_key": "example-value", "allowed_ip": "192.168.1.1"}'

Spec fields:
  description (string)
  public_key (string) [required]
  allowed_ip (string) [required]
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateWireGuardPeerRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateWireGuardPeer(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create WireGuardPeer: %w", err)
		}

		return printOutput(item)
	},
}

var wireguardpeerUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing WireGuardPeer",
	Long: `Update an existing WireGuardPeer.

Examples:
  # Update from stdin
  echo '{"description": "Example description", "public_key": "example-value", "allowed_ip": "192.168.1.1"}' | client wireguardpeer update <uid>

  # Update with --spec flag
  client wireguardpeer update <uid> --spec '{"description": "Example description", "public_key": "example-value", "allowed_ip": "192.168.1.1"}'

Spec fields:
  description (string)
  public_key (string) [required]
  allowed_ip (string) [required]
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateWireGuardPeerRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateWireGuardPeer(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update WireGuardPeer: %w", err)
		}

		return printOutput(item)
	},
}

var wireguardpeerPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a WireGuardPeer",
	Long: `Patch an existing WireGuardPeer spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client wireguardpeer patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client wireguardpeer patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client wireguardpeer patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client wireguardpeer patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchWireGuardPeer(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch WireGuardPeer: %w", err)
		}

		return printOutput(item)
	},
}

var wireguardpeerDeleteCmd = &cobra.Command{
	Use:   "delete [uid...]",
	Short: "Delete one or more WireGuardPeer resources",
	Long: `Deletes one or more WireGuardPeer resources.

You can provide multiple UIDs separated by spaces to delete them all in a single command.
Each UID is processed one by one as an individual, atomic delete operation. If any deletion fails, the command will still attempt to delete the remaining UIDs and report the errors at the end.`,
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		var errs []error
		for _, uid := range args {
			if err := c.DeleteWireGuardPeer(ctx, uid); err != nil {
				errs = append(errs, fmt.Errorf("failed to delete WireGuardPeer %q: %w", uid, err))
				continue
			}
			fmt.Printf("WireGuardPeer %s deleted successfully\n", uid)
		}

		if len(errs) > 0 {
			var errMsgs []string
			for _, e := range errs {
				errMsgs = append(errMsgs, e.Error())
			}
			return fmt.Errorf("encountered %d error(s) during deletion:\n%s", len(errs), strings.Join(errMsgs, "\n"))
		}
		return nil
	},
}

func init() {
	wireguardpeerCmd.AddCommand(wireguardpeerListCmd)
	wireguardpeerCmd.AddCommand(wireguardpeerGetCmd)
	wireguardpeerCmd.AddCommand(wireguardpeerCreateCmd)
	wireguardpeerCmd.AddCommand(wireguardpeerUpdateCmd)
	wireguardpeerCmd.AddCommand(wireguardpeerPatchCmd)
	wireguardpeerCmd.AddCommand(wireguardpeerDeleteCmd)

	// Add spec flag for create and update commands
	wireguardpeerCreateCmd.Flags().String("spec", "", "WireGuardPeer specification in JSON format")
	wireguardpeerUpdateCmd.Flags().String("spec", "", "WireGuardPeer specification in JSON format")

	// Add patch command flags
	wireguardpeerPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	wireguardpeerPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	wireguardpeerPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	wireguardpeerPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	wireguardpeerPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	wireguardpeerPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}
